### ISSUE TITLE
solid tiles are partially missing from .mbtiles db

### ISSUE THREAD

**Issue by sk1p** [tilemill-project/tilemill#1368]
Solid tiles are written to the `images` table, but missing from `map`:

```
sqlite> SELECT i.tile_id FROM images i WHERE NOT EXISTS (SELECT m.tile_id FROM map m WHERE m.tile_id = i.tile_id);
-4294496767
-3099380991
-2982664447
-2849236735
-3706501631
-3924421119
-3891317503
-4243119871
-3604717823
-2798971391
-3538528511
-4244172287
sqlite>
```

No `failed` tiles in the `.export` stats.

**Comment by paulovieira** [comment]
For anyone who arrives here after googling "mbtiles missing tiles": I had a similar problem (solid tiles missing) but solved it by simply using a metatile value of 1. However metatiles of 1 might give rise to other problems related to labels, see: https://www.mapbox.com/tilemill/docs/guides/metatiles/

In that case adjusting `buffer-size` might be needed.
