### ISSUE TITLE
Cannot Export anything on Windows

### ISSUE THREAD

**Issue by tommueller** [tilemill-project/tilemill#1834]
Hi there,

I cannot Export (except of Mapnik.xml) any of my Projects with Tilemill (0.10.1) on Win7.
No matter what kind of format (png, pdf, svg), it always ends with a generic error (Export failed. See log for details). But also the log does not say much:

[tilemill] [tilemill] no crash logs found
[tilemill] [millstone] processing style 'style.mss'
[tilemill] [millstone] processing style 'borders.mss'
[tilemill] [millstone] processing style 'highway.mss'
[tilemill] [millstone] processing style 'pois'
[tilemill] [millstone] processing style 'labels.mss'
[tilemill] [millstone] processing layer 'world'
[tilemill] [millstone] processing layer 'land'
[tilemill] [millstone] processing layer 'ne-lakes'
[tilemill] [millstone] processing layer 'ne-admin-1'
[tilemill] [millstone] processing layer 'ne-admin-0'
[tilemill] [millstone] detected extension of '.zip' for 'C:\Users\newnoise\Documents\MapBox\cache\39906004-world_borders_merc\39906004-world_borders_merc.zip'
[tilemill] [millstone] detected extension of '.zip' for 'C:\Users\newnoise\Documents\MapBox\cache\77e50cb0-lakes\77e50cb0-lakes.zip'
[tilemill] [millstone] detected extension of '.zip' for 'C:\Users\newnoise\Documents\MapBox\cache\60bcb61f-admin_1_states_provinces_lines_shp\60bcb61f-admin_1_states_provinces_lines_shp.zip'
[tilemill] [millstone] detected extension of '.zip' for 'C:\Users\newnoise\Documents\MapBox\cache\491a515b-admin_0_boundary_lines_land\491a515b-admin_0_boundary_lines_land.zip'
[tilemill] [millstone] finished processing 'C:\Users\newnoise\Documents\MapBox\project\JoinJackGreyScale'
[tilemill] [tilemill-ui] Note: Unknown option "updatesVersion" in config file.
[tilemill] [tilemill-ui] Note: Unknown option "updatesTime" in config file.
[tilemill] [tilemill-ui] [millstone] processing style 'style.mss'
[tilemill] [tilemill-ui] [millstone] processing style 'borders.mss'
[tilemill] [tilemill-ui] [millstone] processing style 'highway.mss'
[tilemill] [tilemill-ui] [millstone] processing style 'pois'
[tilemill] [tilemill-ui] [millstone] processing style 'labels.mss'
[tilemill] [tilemill-ui] [millstone] processing layer 'world'
[tilemill] [tilemill-ui] [millstone] processing layer 'land'
[tilemill] [tilemill-ui] [millstone] processing layer 'ne-lakes'
[tilemill] [tilemill-ui] [millstone] processing layer 'ne-admin-1'
[tilemill] [tilemill-ui] [millstone] processing layer 'ne-admin-0'
[tilemill] [tilemill-ui] [millstone] detected extension of '.zip' for 'C:\Users\newnoise\Documents\MapBox\cache\39906004-world_borders_merc\39906004-world_borders_merc.zip'
[tilemill] [tilemill-ui] [millstone] detected extension of '.zip' for 'C:\Users\newnoise\Documents\MapBox\cache\77e50cb0-lakes\77e50cb0-lakes.zip'
[tilemill] [tilemill-ui] [millstone] detected extension of '.zip' for 'C:\Users\newnoise\Documents\MapBox\cache\60bcb61f-admin_1_states_provinces_lines_shp\60bcb61f-admin_1_states_provinces_lines_shp.zip'
[tilemill] [tilemill-ui] [millstone] detected extension of '.zip' for 'C:\Users\newnoise\Documents\MapBox\cache\491a515b-admin_0_boundary_lines_land\491a515b-admin_0_boundary_lines_land.zip'
[tilemill] [tilemill-ui] [millstone] finished processing 'C:\Users\newnoise\Documents\MapBox\project\JoinJackGreyScale'
[tilemill] Export process failed
[tilemill] [tilemill] no crash logs found

Thanks for any help!
tom

**Comment by ginsent** [comment]
Whoa, this bug is 2 years old and still unresolved.

**Comment by ayratinirani** [comment]
4 yaers

**Comment by tmcw** [comment]
Happy to accept a PR. Yep, this is a long, outstanding ticket, and it'd be nicer if it was fixed, but time and people are finite. If this is a very high priority for you, please contribute a pull request and make it happen, rather than commenting about the fact that it hasn't happened.
