### ISSUE TITLE
incorrect rendering of holes in GeoJSON polygons

### ISSUE THREAD

**Issue by tyrasd** [tilemill-project/tilemill#2110]
When rendering polygons from a GeoJSON data layer, only some of the holes get rendered correctly. The rest gets an outline but is filled like the rest of the polygon.

Here is a cut-out of the rendering of a single [large (multi)polygon](https://gist.github.com/tyrasd/7107051) containing several holes.
![auswahl_060](https://f.cloud.github.com/assets/1927298/1384731/61fcb104-3b53-11e3-82d5-8c2d73da3a1e.png)

Taking a deeper look at the data, I notice that all the incorrectly filled holes have clockwise point order. But as of the [geojson specs](http://geojson.org/geojson-spec.html#polygon) point order shouldn't matter.

**Comment by RAytoun** [comment]
Can you let me know what the final outcome is for the winding of polygons. I can then teach new mappers from the start to do all polygons as clockwise/anti-clockwise so that if an inner is required at any stage the outer direction will be correct. Thanks.

**Comment by pnorman** [comment]
This issue is about geojson and other mapnik datasources, and not something that OSM mappers need to worry about when mapping. The only time winding order matters for ways is coastlines, where it's land on the left, but the reasons are entirely unrelated to Mapnik.

**Comment by RAytoun** [comment]
OK Thanks Paul.

**Comment by springmeyer** [comment]
Re-reading this ticket and will summarize my understanding:

 - Some applications, depending on how they store geometries, may care about winding order and some may not (need to) care.
 - Same goes for formats in practice: depending on the way the format encodes polygon geometries the winding order may or may not (need to) matter.
 - GeoJSON does not specify a required winding order for polygons: therefore to correctly interpret polygons with holes (interior rings) decoding applications need to treat the first array as the exterior ring and all following arrays as interior rings.
 - The original rendering bug in Mapnik (causing the incorrect polygon filling in Tilemill) resulted from Mapnik using `agg::filling_rule_e::fill_non_zero` for `agg::rasterizer_scanline_aa` which expects that polygons will have[ interior rings with a different winding order](https://github.com/mapnik/mapnik/blob/master/deps/agg/include/agg_rasterizer_scanline_aa.h#L89-L96). The solution could have been to detect GeoJSON interior rings and ensure their winding order was reversed, but instead we went with a simpler approach of using `agg::filling_rule_e::fill_even_odd` which does not depend on winding order to draw holes. In the future we may revisit this.
 - When winding order matters for geometry encoding, there is generally consensus that the winding order of the exterior ring should be the opposite of the interior rings. However, some applications prefer RRH (right hand rule) and some prefer LHR (left hand rule).
 - There is some contradicting details however in the comments above about what the terms RRH and LHR actually imply about winding order.
   - PostGIS  [ST_ForceRHR doc](http://postgis.net/docs/manual-dev/ST_ForceRHR.html) says RHR == CW for exterior ring, CCW for interior rings
   - @rcoup confirms the postgis doc [here](https://github.com/mapbox/tilemill/issues/2110#issuecomment-30631558) that RHR == CW for exterior ring, CCW for interior rings.
   - @sgillies [says here](https://github.com/mapbox/tilemill/issues/2110#issuecomment-30674206)  that RHR == CCW for exterior ring, CW for interior rings
   - The [KML Spec](https://developers.google.com/kml/documentation/kmlreference#polygon) confirms @sgillies that RHR = CCW oriented coordinates.
   - Luckily [XKCD clears up this confusion up completely](http://xkcd.com/199/)
 - More important than differences in terminology, the important thing about polygon winding order is that a spec state clearly the expected orientation of exterior and interior rings. The current plan is `CCW exterior, CW interior` for vector tiles as per https://github.com/mapbox/mapnik-vector-tile/issues/59.

**Comment by artemp** [comment]
>The current plan is CCW exterior, CW interior for vector tiles as per mapbox/mapnik-vector-tile#59.

CCW for exterior ring and CW for interior rings is in sync with OGC/ISO specs : 
@springmeyer  - surprised PostGIS is not compliant with (see below)

```text
6.1.11 Polygon, Triangle
6.1.11.1 Description
A Polygon is a planar Surface defined by 1 exterior boundary and 0 or more interior boundaries. Each interior boundary defines a hole in the Polygon. A Triangle is a polygon with 3 distinct, non-collinear vertices and no interior boundary.
The exterior boundary LinearRing defines the “top” of the surface which is the side of the surface from which the exterior boundary appears to traverse the boundary in a counter clockwise direction. The interior LinearRings will have the opposite orientation, and appear as clockwise when viewed from the “top”,
The assertions for Polygons (the rules that define valid Polygons) are as follows:
a) Polygons are topologically closed;
b) The boundary of a Polygon consists of a set of LinearRings that make up its exterior and interior boundaries;
c) No two Rings in the boundary cross and the Rings in the boundary of a Polygon may intersect at a Point but only as a tangent, e.g.
26 Copyright © 2010 Open Geospatial Consortium, Inc.
∀ P ∈ Polygon, ∀ c1,c2∈P.Boundary(), c1≠c2,
∀ p,q ∈Point,p,q ∈ c1,p ≠ q, [p∈c2]⇒[∃ δ>0∋[|p-q|<δ]⇒[q∉c2]];
Note: This last condition says that at a point common to the two curves, nearby points cannot be common. This forces each common point to be a point of tangency.
d) A Polygon may not have cut lines, spikes or punctures e.g.:
∀ P ∈ Polygon, P = P.Interior.Closure;
e) The interior of every Polygon is a connected point set;
f) The exterior of a Polygon with 1 or more holes is not connected. Each hole defines a connected component of the exterior.
In the above assertions, interior, closure and exterior have the standard topological definitions. The combination of (a) and (c) makes a Polygon a regular closed Point set. Polygons are simple geometric objects. Figure 11 shows some examples of Polygons.
```

**Comment by strk** [comment]
PostGIS does not care about orientation.

It does have an ST_ForceRHR function to force the "right-hand-rule"
where the rule is defined as "area is on the right as you walk on the edge",
which makes shells clockwise and holes counterclockwise.

Is there any definition of "right-hand-rule" in OGC ?

You can obtain the reverse ordering ST_Reverse(ST_ForceRHR(geom))

**Comment by sgillies** [comment]
@strk the KML's "right-hand rule" is from [André-Marie Ampère](http://en.wikipedia.org/wiki/Right-hand_rule#Ampere.27s_right_hand_screw_rules), not the OGC. Imagine the fingers of your right hand curling around the polygon's exterior with your thumb pointing "up", signing a positive area for the polygon in the signed area sense.

**Comment by pramsey** [comment]
"Right hand rule" as defined by PostGIS inherits from a BC government data quality rule for data capture, which was described as "right hand rule" (right hand in the area of interest as you walk the line) but is in fact the opposite of "right hand rule" as understood by computer graphics people and most others. I think the FME also inherited this terminological snafu from BC. As @strk notes, internally PostGIS/JTS/GEOS/OGC/WKT/WKB don't make any assumptions about winding order.
