### ISSUE TITLE
"Error: bad allocation" without any details on exporting larger image to PNG (working on geojson data)

### ISSUE THREAD

**Issue by matkoniecz** [tilemill-project/tilemill#2132]
3000x3000 px worked, larger like 4000x4000 px or 8000x8000 px failed with this mysterious error.

TileMill 0.10.1

**Comment by prasadareddy21** [comment]
How do i solve this problem though?

**Comment by matkoniecz** [comment]
> You are running out of memory.

Add more memory.

**Comment by OLIVERSKOVDAL** [comment]
But if i have over 40GB of memory left, then surely lack of memory isn't the case? I have the same problem and i can't fix it. 4 minute video, 1080p, 60fps. Shouldn't take 40GB right?

**Comment by csytsma** [comment]
If you're getting this error running the Windows app version 0.10.x, I'd recommend trying the new v1.0.x version, non-platform specific.
