### ISSUE TITLE
Emoji, Mro, and other 4-byte Unicode chars

### ISSUE THREAD

**Issue by mapmeld** [tilemill-project/tilemill#2138]
I made a rare-language map in the past, and was hoping to create a new one with Mro, a language just added to Unicode. Fortunately there's a font (http://phjamr.github.io/mro.html). Unfortunately, like Emoji, its part of Unicode uses extra bytes which are difficult to handle in V8/Node.js and they do not appear in TileMill.  https://gist.github.com/mranney/1707371

I know this is a rare use case, so I'll research the solution, but first I'm filing an issue to see if someone knows where to start, whether it's fixed in TileMill 2, or maybe whether this will be too complex and I should just hack the font to move the characters into reach.
### what is wrong

When I add a label with an Emoji, it appears as two boxes on the map. In the feature table, it shows a missing character symbol. If I set the font to Apple Color Emoji Regular, it is still blank. The error is due to a larger V8/Node.js problem, not a font problem.
### beyond Emoji

Languages already in Unicode, plus languages like Mro which are being added, use more than two bytes. http://www.unicode.org/alloc/Pipeline.html is a list with Mro going from 16A40 to 16A6F. Several of these languages are used by thousands of people, so it would be cool if a map could be made in TileMill.
### possible solutions
- There are node modules for emoji. If they have a general solution that works for Mro, that would be awesome!
- Moving the letters within the font
- Generating label tiles in Firefox and other non-V8 browsers

**Comment by chivasblue** [comment]
@springmeyer Do you still have the harfbuzz package someplace?
https://launchpad.net/~mapnik/+archive/harfbuzz is returning not found.

Thanks!

**Comment by springmeyer** [comment]
@chivasblue - you don't need it. Latest TileMill master uses node-mapnik binaries that bundle Mapnik with harfbuzz linked in.

**Comment by chivasblue** [comment]
@springmeyer  Thanks for the quick response, however I am facing the below issue.
The value in my Postgresql database is "सांताक्रुज़", see below image:
![sql workbench-j mapserver 13 - default wksp _003](https://cloud.githubusercontent.com/assets/7068890/14499535/527011a4-01bc-11e6-94d5-3a8c7e675128.png)

However, in my layer the value is displayed as in below snapshot:
![tilemill_004](https://cloud.githubusercontent.com/assets/7068890/14499542/594c431c-01bc-11e6-853c-15ec72c02ead.png)


I used the default installation tilemill package from the mapbox website. The OS is Ubuntu 14.04 LTS Trusty.
The mapnik version which seems to be installed with tilemill is
mapnik-config -v
2.3.0-pre

I have tried all the hindi fonts, however none seem to fix the issue. Any help or pointers will be highly appreciated!

Thanks!

**Comment by springmeyer** [comment]
@chivasblue - you need to use TileMill master and install it manually like https://github.com/mapbox/tilemill#installation

**Comment by chivasblue** [comment]
@springmeyer - Thanks, will try and let know.

**Comment by chivasblue** [comment]
@springmeyer - I was able to install tilemill from source, however now when I launch I get the below messages

user@ubuntu:~/python-mapnik-master/node-v0.10.13/tilemill$ ./index.js
Mapnik LOG> 2016-04-14 04:29:53: Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
Mapnik LOG> 2016-04-14 04:29:56: Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
Mapnik LOG> 2016-04-14 04:29:56: Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
Mapnik LOG> 2016-04-14 04:29:56: Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
[tilemill] Mapnik LOG> 2016-04-14 04:29:56:
[tilemill] Mapnik LOG> 2016-04-14 04:29:56: Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
[tilemill]  
[tilemill] Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
[tilemill] 
[tilemill] Mapnik LOG> 2016-04-14 04:29:58:
[tilemill]  
[tilemill] Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
[tilemill] 
[tilemill] Mapnik LOG> 2016-04-14 04:29:58:
[tilemill]  
[tilemill] Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
[tilemill] 
[tilemill] Mapnik LOG> 2016-04-14 04:29:59:
[tilemill]  
[tilemill] Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
[tilemill] 
[tilemill] Mapnik LOG> 2016-04-14 04:29:59:
[tilemill]  
[tilemill] Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
[tilemill] 
[tilemill] Mapnik LOG> 2016-04-14 04:29:59:
[tilemill]  
[tilemill] Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
[tilemill] 
[tilemill] Mapnik LOG> 2016-04-14 04:29:59:
[tilemill]  
[tilemill] Problem loading plugin library: /usr/lib/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
[tilemill] 
[tilemill] Creating configuration dir /home/orphin/.tilemill
[tilemill] Creating files dir /home/orphin/Documents/MapBox
[tilemill] Creating export dir /home/orphin/Documents/MapBox/export
[tilemill] Creating project dir /home/orphin/Documents/MapBox/project
[tilemill] Started [Server Tile:20008].
[tilemill] Creating cache dir /home/orphin/Documents/MapBox/cache
[tilemill] Plugin [carto] loaded.
[tilemill] Plugin [editor] loaded.
[tilemill] Plugin [fonts] loaded.
[tilemill] Plugin [templates] loaded.
[tilemill] Started [Server Core:20009].
[tilemill] Client window created (pass --server=true to disable this)
Error parsing options: Cannot open display: 
[tilemill] Closing child process: core (pid:50527)
[tilemill] Closing child process: tile (pid:50529)
[tilemill] Closing child process: client (pid:50537)
Exiting [tilemill]

This machine is a Ubuntu 12.04 Server with no UI, what am I missing here?

Thanks!

**Comment by chivasblue** [comment]
@springmeyer - I installed TileMill master, however I am getting the below error when I try to add a layer:
** Message: console message: http://127.0.0.1:20009/assets/bones/all.js @5553: Invalid index file

What am i missing?

Thanks!

**Comment by chivasblue** [comment]
Update - Solved the "invalid index file" by deleting the existing countries layer, deleting its corresponding shapefile, and selecting a new shapefile. All fonts are being rendered correctly now.
@springmeyer - Thanks a lot for your help!

**Comment by map-123** [comment]
@chivasblue - I am facing the same Hindi font issue as mentioned in trail; can you suggest the possible solution or workaround. I am using tilemill ver0.10.2; mapnik-config -v is 2.3.0-pre.

Thanks in advance

**Comment by mapmeld** [comment]
@map-123 can you use the new MapBox Studio?  Indian languages look good on http://openstreetmap.in/demo/#3.9/23.10/81.00

**Comment by map-123** [comment]
@mapmeld The link you suggested has the name as mentioned in the red circle in the image below.
![hindi_osm](https://cloud.githubusercontent.com/assets/26539993/24133591/f5f48c82-0e23-11e7-8b7a-65ec35b34cef.JPG)
However, we want to display the name as this:

नई दिल्ली

Is there any solution to this issue? 
I am trying to display hindi names using TileMill on Ubuntu 14.04. I would prefer any open source solution to this issue, if possible.

Thank You.
