### ISSUE TITLE
Super big type while exporting as svg

### ISSUE THREAD

**Issue by JolinM** [tilemill-project/tilemill#2225]
I am unable to get the labels text size to not be super huge on the map (Illustrator) or not appear at all (InkScribe). Is this a know bug or some manipulation I don’t get?

Here is my label styling.
```
text-name: [name];
text-face-name: 'Helvetica Neue Regular';
text-fill: #f9c523;
text-size: 12;
text-placement: line;
text-halo-radius: 2;
text-halo-fill: #000;
```
![Super big type](https://f.cloud.github.com/assets/3504842/2298062/c45a0be4-a0b6-11e3-80ef-5c375c05cc9a.png)

**Comment by tmcw** [comment]
Upstream now, let's hope Adobe fixes this. Ping back @JolinM if they do.
