### ISSUE TITLE
New "Point Cluster" functionality

### ISSUE THREAD

**Issue by sfkeller** [tilemill-project/tilemill#2244]
When there are too much icons nearby - especially when zooming out - there occurs the “point clustering problem”. 

I think that could be resolved within TileMill/Mapnik (including rendering and UTFgrid), e.g. by calculating and showing place holders with numbers in it ("cluster icons"). I only found solutions with separate preprocessing. e.g. http://blog.perrygeo.net/2013/09/30/leaflet-simple-csv/ .

**Comment by Komzpa** [comment]
@sfkeller this could be achived modifying your data in SQL before rendering, see http://postgis.net/docs/manual-2.2/ST_ClusterWithin.html.

**Comment by sfkeller** [comment]
Thanks @Komzpa for the hint to this nice new ST_ClusterWithin function which was not available 2014.

You can always preprocess your data. But I think the clustering problem should be solved by a component which sits between the data source and the renderer. In the case of TileMill it could be part of the tile generation process.

BTW: Are you aware of this MB GL JS editor project https://www.kickstarter.com/projects/174808720/maputnik-visual-map-editor-for-mapbox-gl - and these vector tile projects http://osm2vectortiles.org/ and openmaptiles https://github.com/openmaptiles ?

**Comment by Komzpa** [comment]
sure.

There is a layer between data and renderer, that works during rendering - it's called PostGIS :)

It's non-trivial to implement clustering on any other layer in Tilemill's stack. 

(I'm trying to close the hoards of old tickets with maximum profit, sorry for breaking hopes if there were any :)

**Comment by sfkeller** [comment]
Fully understanding you cleaning up :-). Just hopes you could join forces to keep the vector tiles ecosystem as open as possible by supporting the projects I mentioned above.
