### ISSUE TITLE
TileMill wont start

### ISSUE THREAD

**Issue by awolfe76** [tilemill-project/tilemill#2259]
Yesterday I downloaded TileMill for OSX.

When I try to start it I just get the loading 'spinner' (below the TileMill logo).

This is in the log:

Note: Unknown option "updatesVersion" in config file.
Note: Unknown option "updatesTime" in config file.
[tilemill] Note: Unknown option "updatesVersion" in config file.
[tilemill] Note: Unknown option "updatesTime" in config file.
[tilemill] Started [Server Tile:20008].
[tilemill] Plugin [carto] loaded.
[tilemill] Plugin [editor] loaded.
[tilemill] Plugin [fonts] loaded.
[tilemill] Plugin [templates] loaded.
[tilemill] Started [Server Core:20009].

Any ideas?

Thanks.
![screen shot 2014-03-31 at 9 40 01 am](https://cloud.githubusercontent.com/assets/2932572/2567802/022c2656-b8da-11e3-82c2-ccd6abdeb4aa.png)

**Comment by leoxnv** [comment]
It didn't work for me. Any ideas?

MBP-de-Leonel:tilemill leoxnv$ ./index.js
Note: Unknown option "profile" in config file.
[tilemill] Note: Unknown option "profile" in config file.
[tilemill] 
[tilemill] /Users/leoxnv/tilemill/commands/core.bones:101
[tilemill]         throw new Error("Could not set mapnik version to " + mapnik.versions.m
[tilemill]               ^
[tilemill] Error: Could not set mapnik version to 3.0.0
[tilemill]     at command.bootstrap (/Users/leoxnv/tilemill/commands/core.bones:101:15)
[tilemill]     at Command (/Users/leoxnv/tilemill/node_modules/bones/server/command.js:7:10)
[tilemill]     at new child (/Users/leoxnv/tilemill/node_modules/backbone/backbone.js:964:41)
[tilemill]     at Plugin.start (/Users/leoxnv/tilemill/node_modules/bones/server/plugin.js:136:20)
[tilemill]     at Object.exports.start (/Users/leoxnv/tilemill/node_modules/bones/bones.js:28:27)
[tilemill]     at Object.<anonymous> (/Users/leoxnv/tilemill/index.js:41:36)
[tilemill]     at Module._compile (module.js:456:26)
[tilemill]     at Object.Module._extensions..js (module.js:474:10)
[tilemill]     at Module.load (module.js:356:32)
[tilemill]     at Function.Module._load (module.js:312:12)
[tilemill] Error: child process: "core" failed with code "8"
[tilemill] Error: child process: "tile" failed with code "143"
[tilemill] Closing child process: core (pid:27283)
[tilemill] Closing child process: tile (pid:27284)
Exiting [tilemill]

**Comment by springmeyer** [comment]
@leoxnv - sorry, can you `git pull` and then try `node index.js` again now? This should be fixed in https://github.com/mapbox/tilemill/commit/6c8a4f33b32f071ce0035f60f097e0f3a5c067f7

**Comment by leoxnv** [comment]
perfect. Now it works fine. Thank you
