### ISSUE TITLE
Suggestion: automatically wrap SQL subqueries 

### ISSUE THREAD

**Issue by stevage** [tilemill-project/tilemill#2300]
TileMill currently requires SQL queries to be specified as subqueries like this:

```
(select *
from planet_osm_line
where highway='residential') pointless_subquery_name_which_has_no_effect
```

This quirk is a little annoying, and hard to teach people. It also gets messy when there are genuine subqueries (with unions, in particular). Why not automatically wrap the query if it lacks an opening parenthesis (for backward compatibility)?:

```
select *
from planet_osm_line
where highway='residential'
```

**Comment by Komzpa** [comment]
@stevage converted your branch into https://github.com/tilemill-project/tilemill/pull/2579 - is it okay to merge?

**Comment by stevage** [comment]
Hmm I don't have a dev environment and it's been a long time. But you have
my permission!

**Comment by Komzpa** [comment]
@stevage merged that, thanks!
