### ISSUE TITLE
Correct SQL produces an error message with PostGIS plugin

### ISSUE THREAD

**Issue by Zverik** [tilemill-project/tilemill#2308]
Create a PostGIS layer, insert the following SQL:
```sql
(select st_project(pt.pt, 1000, 0)::geometry as way from (select ST_SetSRID(ST_Point(30, 60), 4326) as pt) pt) as scale
```
Put `way` into geometry field and click "Save". You will get the following error message:
```
Postgis Plugin: ERROR:  syntax error at or near ")"
LINE 1: ...ext) FROM (SELECT ST_Extent(way) as ext from (select) as tmp
                                                                ^

in executeQuery Full sql was: 'SELECT ST_XMin(ext),ST_YMin(ext),ST_XMax(ext),ST_YMax(ext) FROM (SELECT ST_Extent(way) as ext from (select) as tmp'
```
If you put some simple valid SQL and then replace it with the given string, it will work with no complaints.

The bug is related to calculating extent. When I use custom extent, there is no error.

**Comment by Komzpa** [comment]
Please set extent manually.

Thanks!
