### ISSUE TITLE
tilemill crashing quite frequent ( child process: "tile" failed with signal "SIGSEGV")

### ISSUE THREAD

**Issue by georgbachmann** [tilemill-project/tilemill#2342]
Hello,
on our installation of tilemill (latest-git pull from here) on a debian machine (running jessie/sid) we see many crashes while "using" tilemill and always while trying to export mbtiles. If you need more information on the machine/os I have to ask...

What I did was I pulled osm-bright and created a project out of it. Furthermore I added some raster data (one file about 300MB and the other about 700MB). Also an other shapefile of about 1GB and one more of about 400MB. I also added another layer from the Postgres DB.

What I am seeing now quite frequent is the following crash:

```
*** Error in `tilemill-tile': double free or corruption (!prev): 0x00007f58be27d220 ***
*** Error in `tilemill-tile': double free or corruption (fasttop): 0x00007f58bcf10440 ***
*** Error in `tilemill-tile': double free or corruption (!prev): 0x00007f58be2c7040 ***
*** Error in `tilemill-tile': double free or corruption (fasttop): 0x00007f58bcf108a0 ***
*** Error in `tilemill-tile': double free or corruption (!prev): 0x00007f58be4a1fa0 ***
*** Error in `tilemill-tile': double free or corruption (fasttop): 0x00007f58bcf124c0 ***
*** Error in `tilemill-tile': double free or corruption (!prev): 0x00007f58be58f750 ***
*** Error in `tilemill-tile': corrupted double-linked list: 0x00007f58c8e3c0c0 ***
[tilemill] Error: child process: "tile" failed with signal "SIGSEGV"
[tilemill] Closing child process: core (pid:1840)
[tilemill] Closing child process: tile (pid:1842)
Exiting [tilemill]
```

I can't find the logfile that the UI is referring to. There is no file in ~/.tilemill.log

I guess it's releated to https://github.com/mapbox/tilemill/issues/1892 and https://github.com/mapbox/tilemill/issues/1617
I already tried out the `cursor_size` option mentioned but that did not have any effect...

Any help is appreciated cause right now we can't export anything from tilemill :)

If this is important: Tilemill is running with --server=true

**Comment by F3L1X79** [comment]
I got the same problem, I know it's been a long time - but could you tell the version of mapnik you use to avoid the problem?
