### ISSUE TITLE
Error while exporting PDF, SVG - SIGABRT

### ISSUE THREAD

**Issue by diegozaks** [tilemill-project/tilemill#2353]
Installed following this guide on OSX 10.9.3, using TileMill v0.10.1:
https://www.mapbox.com/tilemill/docs/guides/osm-bright-mac-quickstart/

Created a map and removed the text labels. 

Error while exporting PDF, SVG (PNG does work), "Export process failed with signal 'SIGABRT' "
![screenshot 2014-06-16 14 55 27](https://cloud.githubusercontent.com/assets/5490602/3291766/d247be10-f587-11e3-918f-87727ba370a2.png)

**Comment by ginsent** [comment]
Same with me. Doesn't export to svg/pdf if only there's one text in the map. Without texts it works okay.
