### ISSUE TITLE
Unable to open tilemill on OSX 10.10 Yosemite.

### ISSUE THREAD

**Issue by willpaige** [tilemill-project/tilemill#2356]
Application initiatives, but nothing happens after the loading wheel appears. 
![screen shot 2014-06-26 at 16 04 38](https://cloud.githubusercontent.com/assets/3032885/3400189/37065f4c-fd43-11e3-9cfe-1fa192ccdf2a.png)

**Comment by datafunk** [comment]
Following the advice from https://github.com/mapbox/tilemill/issues/2380 (https://github.com/mapbox/tilemill#installation) neither desktop app or CLI option works on 10.10.2 - I had a MapBox Studio 0.2.0 hanging around though and that booted up ok

during the npm install process the followings occurred:
---------
opcube currently does not support darwin
---------
then, when running ./index.js in node, all config options threw errors:
---------
Note: Unknown option "profile" in config file.
Note: Unknown option "updates" in config file.
Note: Unknown option "updatesTime" in config file.
Note: Unknown option "updatesVersion" in config file.
Note: Unknown option "httpProxy" in config file.
---------

**Comment by gabssnake** [comment]
I get the endless spinning on OS X 10.11.3 with Tilemill v0.10.1.
Can provide useful information ?

**Comment by teeschke** [comment]
Same issue with TileMill 0.10.1 on OSX 10.11.1 
=> endless spinning!

**Comment by teeschke** [comment]
I see that TileMill is not supported anymore. 
Seems I have to use Mapbox Studio Classic instead.
Thanks and regards

**Comment by daspecster** [comment]
Same issue in OSX 10.11.4.

**Comment by jerald-acacus** [comment]
I was able to get through this by downloading TileMill-0.10.0 from http://tilemill.s3.amazonaws.com/index.html?path=archive/. Install it and when it gets to the endless spinning part go to **Update Preferences** (Under Check for Updates) in the menu. Then turn on **Install Developer Builds** and do an update.

**Comment by gabssnake** [comment]
I can confirm that @jerald-acacus ’ solution works under Mac OS X 10.11.3 with Tilemill v0.10.1, see #2550

**Comment by MattWilliamsDev** [comment]
@jerald-acacus That solution works on 10.11.5 also.
