### ISSUE TITLE
Tilemill crashing quite frequently with "FATAL ERROR: Evacuation Allocation failed - process out of memory"

### ISSUE THREAD

**Issue by georgbachmann** [tilemill-project/tilemill#2394]
Lately Tilemill is crashing on every export I try to do.
I always get the same error:

    [tilemill] FATAL ERROR: Evacuation Allocation failed - process out of memory
    [tilemill] Error: child process: "core" failed with signal "SIGABRT"
    [tilemill] Closing child process: core (pid:1516)
    [tilemill] Closing child process: tile (pid:1518)
    Exiting [tilemill]

Any ideas on how I could solve this? The machine has about 50GB of memory... So i guess memory shouldn't be the big problem here???

And... __Another super important question__: I'd like to make an export of a map with the size of Europe soon. If Tilemill would crash in the middle that wouldn't be too good as it seems I can't resume a crashed export?!? At least I didn't find anything like "Resume export" in the UI?!?

**Comment by Komzpa** [comment]
sorry, not actionable. would you please try again with new tilemill from master and open another issue if problem persists?
