### ISSUE TITLE
Mapbox Install Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by chriscalip** [tilemill-project/tilemill#2427]
[redacted]:~/Downloads$ ./install-tilemill.sh 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Err http://ppa.launchpad.net trusty/main amd64 Packages
  404  Not Found
Err http://ppa.launchpad.net trusty/main i386 Packages
  404  Not Found
Ign http://ppa.launchpad.net trusty/main Translation-en_US
Ign http://ppa.launchpad.net trusty/main Translation-en
Fetched 1,432 kB in 4s (293 kB/s)
W: Failed to fetch http://ppa.launchpad.net/ubuntugis/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/ubuntugis/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Press [ENTER] to quit.
[redacted]:~/Downloads$ ll

**Comment by MichaelKloepzig** [comment]
I can reproduce this error with Xubuntu 14.04:
```
W: Failed to fetch http://ppa.launchpad.net/developmentseed/mapbox/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/developmentseed/mapbox/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found
```

**Comment by FearMediocrity** [comment]
I can reproduce on Ubuntu Server 14.10

    Err http://ppa.launchpad.net utopic/main amd64 Packages
    404  Not Found
    Get:3 http://security.ubuntu.com utopic-security/main Sources [44.6 kB]
    Err http://ppa.launchpad.net utopic/main i386 Packages
    404  Not Found


    W: Failed to fetch http://ppa.launchpad.net/developmentseed/mapbox/ubuntu/dists/utopic/main/binary-    amd64/Packages  404  Not Found

    W: Failed to fetch http://ppa.launchpad.net/developmentseed/mapbox/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found

**Comment by chriscalip** [comment]
spring cleaning..
