### ISSUE TITLE
ENOENT, readdir problem

### ISSUE THREAD

**Issue by antoniodelisiis** [tilemill-project/tilemill#2451]
![problem tilemill](https://cloud.githubusercontent.com/assets/10155362/5395723/339de1e4-814c-11e4-8e2c-fc7235835500.jpg)

Hi, after following this guide "https://www.mapbox.com/tilemill/docs/guides/osm-bright-mac-quickstart/#step-2-download--import-osm-data" step by step, and after the step number 3, when I open TileMill and I go on the new map appears this message “ENOENT, readdir '/Users/apple/Downloads/mapbox-osm-bright-5f237ac/shp/land-polygons-split-3857'“

I state that I have already read various discussions, but I can't solve the problem.
Someone can help me?

**Comment by SolomonBier** [comment]
Same issue
