### ISSUE TITLE
launch path not accessible - OS X

### ISSUE THREAD

**Issue by justingreerbbi** [tilemill-project/tilemill#2461]
Hey all,

I am trying to run Tilemill from source on Yosemite 10.10 and get the starting window but nothing else. 

Here is what I tried:
Build from source (master)
*make clean
*make run (moved to applications folder)
Error console is showing "launch path not accessible" and app just sits with spinning wheel.

I attempted to launch ./index.js from root directory then visited localhost in browser with no luck as well (no errors in console other than the general profile error).

**Comment by springmeyer** [comment]
Using tilemill latest from github master branch is correct for running on 10.10 for now.

> *make clean
> *make run (moved to applications folder)

I'm confused, are you running those in https://github.com/mapbox/tilemill/tree/master/platforms/osx? If so, don't: the app has not be built in a while so I don't trust it will work. Instead just install from source and run with `./index.js` as described at https://github.com/mapbox/tilemill#installation

**Comment by justingreerbbi** [comment]
Thanks for the reply. I did try running from platform/osx as well as from source. From source it is looks to be running but no errors and no server at localhost. I am going to play around with it a bit more when I get home but though I would mention the error I was getting.

Thanks again

**Comment by EsimioJ** [comment]
Hi all, 
same issue here.
I'm on yosemite.
I've downloaded the zip from mapbox.com, installed in the usual OS X way, drop the app in application folder.
When I launch it starts but get stuck as soon as the window opens.

the consolle is saying:
Note: Unknown option "profile" in config file.
Note: Unknown option "profile" in config file.
Note: Unknown option "profile" in config file.
Note: Unknown option "updatesVersion" in config file.
Note: Unknown option "updatesTime" in config file.
Note: Unknown option "profile" in config file.
Note: Unknown option "updatesVersion" in config file.
Note: Unknown option "updatesTime" in config file.
 
Then I've done what you suggest here:  https://github.com/mapbox/tilemill#installation
git clone git@github.com:mapbox/tilemill.git
cd tilemill
npm install

but there was a problem with the git.. sorry now I don't remember the error..

then i've followed this tut: http://www.the-nerd.be/2014/12/01/run-mapbox-tilemill-on-osx-yosemite-10-10/

and now if i run run.sh in the terminal TileMill opens in safari (not chrome!) http://localhost:20009.

however in the terminal there are some issues:
Booting Tilemill node server
Waiting for server to boot
Note: Unknown option "profile" in config file.
Note: Unknown option "updatesVersion" in config file.
Note: Unknown option "updatesTime" in config file.
[tilemill] Note: Unknown option "profile" in config file.
[tilemill] Note: Unknown option "updatesVersion" in config file.
[tilemill] Note: Unknown option "updatesTime" in config file.
[tilemill] Started [Server Tile:20008].
[tilemill] Plugin [carto] loaded.
[tilemill] Plugin [editor] loaded.
[tilemill] Plugin [fonts] loaded.
[tilemill] Plugin [templates] loaded.
[tilemill] Started [Server Core:20009].

Opening browser

now I can use TileMill in the browser, but open it is a bit awkward :)
and I can't use the quicklook and the spotlight plugins that would be useful to check map.mbtiles.db

maybe if I could set profile, updateVersion and updateTime the application could start?!

thanks for the great software, please help us to get it running on new osx

**Comment by Winter-Lu** [comment]
好的
