### ISSUE TITLE
Shape Plugin: wrong file code : 794129253 

### ISSUE THREAD

**Issue by kalevkylaase** [tilemill-project/tilemill#2466]
My projects were all working fine on TileMill. Then I had to replace my hard drive, the file were all ok. Copied everything to the new hard drive, but now the projects don't open up anymore.

TileMill is giving me error: <b>"Shape Plugin: wrong file code : 794129253. Encountered during parsing of layer 'shoreline_300' in Layer at line 32" </b>

What could be wrong?

**Comment by springmeyer** [comment]
The shapefiles are corrupt. Looks like these may be ones from an old osm-bright project? I'd recommend replacing them with these shapefiles: https://github.com/mapbox/osm-bright#1-download-shapefiles

**Comment by kalevkylaase** [comment]
Not sure if that's the case. I can build new project with exactly the same shapefiles and css files then everything works fine, but I have to make it manually. If i open the old project files with exactly the same layers, shapefiles & css structure then it gives me the error.

Looks like something to do with the project files for me. But was working fine before i copied the files to a new HD.

**Comment by springmeyer** [comment]
You might try clearing the `~/Documents/MapBox/cache` folder (https://www.mapbox.com/tilemill/docs/manual/files-directories/#directory-overview) and see if that fixes things.

**Comment by kalevkylaase** [comment]
still the same. at least i figured out a way how to recover the maps, I need to recover only 3 right now, so it's not so big issue, but just really weird.
