### ISSUE TITLE
line-smooth and polygon-smooth don't match

### ISSUE THREAD

**Issue by cmyk** [tilemill-project/tilemill#2485]
If I use this on forest:
`polygon-smooth:0.5;
line-smooth:0.5;`
I get non-congruent outlines.
The polygon-smooth seems to be the problem.
![screen shot 2015-02-26 at 14 35 08](https://cloud.githubusercontent.com/assets/62413/6392869/3711c5f6-bdc5-11e4-9b7c-1a7186eeb2d6.png)

**Comment by Komzpa** [comment]
would you please report this issue to Mapnik repo?
 github.com/mapnik/mapnik 
thanks!
