### ISSUE TITLE
Error when trying to export

### ISSUE THREAD

**Issue by darlacameron** [tilemill-project/tilemill#2501]
I encountered an error:
```
[tilemill] { [Error: connect ECONNREFUSED]
[tilemill]   code: 'ECONNREFUSED',
[tilemill]   errno: 'ECONNREFUSED',
[tilemill]   syscall: 'connect' }

```

**Comment by Komzpa** [comment]
@darlacameron sorry, not actionable without context. would you please try again with new tilemill from master and open another issue if problem persists?
