### ISSUE TITLE
Imposm Importing Error : violates check constraint " enforce_dims_geometry"

### ISSUE THREAD

**Issue by JeongJun-Lee** [tilemill-project/tilemill#2505]
To use a TileMill for creating offline map from OSM data, when I followed the ubuntu quick start guide, https://www.mapbox.com/tilemill/docs/guides/osm-bright-ubuntu-quickstart/, I met error messages during importing PBF file downloaded with imposom.

There are environment where I am tested.
OS: Ubuntu: 12.04
postgres: 9.1
postgist: 1.5
imposm: 2.3.2 installed by apt-get
python-shapely: 1.2.14-1 installed by apt-get

all error massages like this:

[08:55:02] ## writing data
[2015-04-08 08:55:02,200] imposm.db.postgis - WARNING - error while importing "(
2230985, <psycopg2._psycopg.Binary object at 0x1628f38>, None, u'yes', 5263.6185
71278321)": new row for relation "osm_new_buildings" violates check constraint "
enforce_dims_geometry"

Could anybody let me know how to fix it?

Thanks,
JJ

**Comment by Komzpa** [comment]
not an issue of Tilemill.
@JeongJun-Lee please get your distribution upgrade imposm package to imposm3 https://github.com/omniscale/imposm3
