### ISSUE TITLE
compilation error nodejs 0.12.2

### ISSUE THREAD

**Issue by noog** [tilemill-project/tilemill#2506]
hell i have this error

whant can i do ?

==> Starting package()...
npm info it worked if it ends with ok
npm info using npm@2.7.5
npm info using node@v0.12.2
npm info prepublish tilemill@0.10.1
npm info install tilemill@0.10.1 into /data/build/tilemill-git/btmp/pkg/tilemill-git/usr/lib
npm info installOne tilemill@0.10.1
npm ERR! Linux 3.18.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-d" "-g" "--user" "root" "--prefix" "/data/build/tilemill-git/btmp/pkg/tilemill-git/usr" "--python=/usr/bin/python2"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ENOTSUP

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your version of node/npm: tilemill@0.10.1
npm ERR! notsup Required: {"node":"0.8.x || 0.10.x"}
npm ERR! notsup Actual:   {"npm":"2.7.5","node":"0.12.2"}

npm ERR! Please include the following file with any support request:
npm ERR!     /data/build/tilemill-git/btmp/src/tilemill/npm-debug.log
==> ERROR: A failure occurred in package().
    Aborting...

**Comment by Komzpa** [comment]
sorry, not actionable without context. would you please try again with new tilemill from master and open another issue if problem persists?
