### ISSUE TITLE
Raster Edge Error

### ISSUE THREAD

**Issue by IReese** [tilemill-project/tilemill#2510]
Hi Mapbox,

I am running TileMill 0.11.0 for Windows x64 from the atom shell.  My OS is Windows 7 with Intel Core i7-3687U, 16GB RAM.  My issue is best described in the attached image. Raster edges are rendered incorrectly.  In the past, I had this issue with both Linux and Windows versions of TileMill.  Something similar happened in the previous build of TileMill for Linux and if I recall correctly, there was an issue linked to using the most current version of GDAL.  When we built from source code and built Tilemill to an older version of GDAL, this rendering issue was resolved. 

I wish I could provide more information, however, the solution went undocumented and we really didn't think it would work.

Attached is an image issue.

![rasteredge_error](https://cloud.githubusercontent.com/assets/9852135/7508334/df39962a-f4d2-11e4-8b73-ee35c91a11da.png)

**Comment by IReese** [comment]
One additional comment is this only happens when the 'Advanced' settings of the .vrt added to Tilemill are set to band="1".

**Comment by IReese** [comment]
This is also an issue in the latest Linux version as well.

**Comment by bsudekum** [comment]
@IReese can you try to increase the raster mesh size?

`raster-mesh-size: 100000;`

**Comment by IReese** [comment]
Hi Bobby,

Unfortunately, raster mesh does not work in this instance.  It shifts the raster edges but does not remove the edge lines.  Furthermore, it shifts the raster itself and no longer lines up with the underlying data.  I attached a screen shot of the outcome.

Cheers.
![rastermesh](https://cloud.githubusercontent.com/assets/9852135/7714426/91db6caa-fed2-11e4-9856-f8cb05e0e7df.jpg)

**Comment by palmerj** [comment]
I think I have narrowed this problem down a little. 

Seems in the new version of TileMill (I'm using MacOSX version on 10.10 from here: https://gist.github.com/bsudekum/b4606871250d9d834b3d) the raster-scaling option is causing the issue. When the option is set to "fast" or "near" the interpolation/rescaling is ok on the edge of raster image:

![fast](https://cloud.githubusercontent.com/assets/580022/8028001/d63bd874-0df7-11e5-9346-ad34d36f620e.png)

However if one of the more advanced scaling options is used (e.g linear, bicubic or lanczos) then a black edge comes up (see black edge on diagonal):

![bicubic](https://cloud.githubusercontent.com/assets/580022/8028019/48520f14-0df8-11e5-97c7-eee98725167a.png)

I have the datasource advanced option band="1" set. The band has only values of either 0 or 127. Nodata is set to 255 but there are none of these values. 

raster details are:
```
gdalinfo hillshademultiple.tif
Driver: GTiff/GeoTIFF
Files: hillshademultiple.tif
       hillshademultiple.tif.aux.xml
Size is 391, 4403
Coordinate System is:
PROJCS["WGS 84 / Pseudo-Mercator",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["X",EAST],
    AXIS["Y",NORTH],
    EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"],
    AUTHORITY["EPSG","3857"]]
Origin = (18467270.898099999874830,-5724779.639170000329614)
Pixel Size = (8.002818158568095,-7.999173479445758)
Metadata:
  AREA_OR_POINT=Area
  Corder=PCRL
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (18467270.898,-5724779.639) (165d53'39.54"E, 45d39' 7.73"S)
Lower Left  (18467270.898,-5760000.000) (165d53'39.54"E, 45d52'22.33"S)
Upper Right (18470400.000,-5724779.639) (165d55'20.73"E, 45d39' 7.73"S)
Lower Right (18470400.000,-5760000.000) (165d55'20.73"E, 45d52'22.33"S)
Center      (18468835.449,-5742389.820) (165d54'30.14"E, 45d45'45.42"S)
Band 1 Block=391x10 Type=Byte, ColorInterp=Gray
  Min=0.000 Max=127.000 
  Minimum=0.000, Maximum=127.000, Mean=60.636, StdDev=63.435
  NoData Value=255
  Metadata:
    STATISTICS_MAXIMUM=127
    STATISTICS_MEAN=60.635501156985
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=63.43535801411
Band 2 Block=391x10 Type=Byte, ColorInterp=Alpha
  Min=0.000 Max=0.000 
  Minimum=0.000, Maximum=0.000, Mean=0.000, StdDev=0.000
  NoData Value=255
  Metadata:
    STATISTICS_MAXIMUM=0
    STATISTICS_MEAN=0
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=0
```

He's the project attached for reference:

https://dl.dropboxusercontent.com/u/30623980/test_raster_edge_test.zip

Also the mapnik used to run the project is here for quick reference:

https://gist.github.com/palmerj/0aa78185d41e37c72777

**Comment by palmerj** [comment]
@springmeyer: Do you have any ideas on this ticket?

**Comment by springmeyer** [comment]
@palmerj - thank you for the great testcase. I was able to replicate locally with the latest Mapnik 3.x code (master). The problem appears to be that after the refactoring done to support https://github.com/mapnik/mapnik/issues/2491 we started colorizing the image **after** scaling. The problem with this approach is that non-nearest neighbor scaling methods may create new pixel values. This is what is happening in your case. A fringe of pixels becomes `1` and then that gets colorized as black when `1` value pixels should not exist.

So, this is a Mapnik bug. I've filed at https://github.com/mapnik/mapnik/issues/2902

**Comment by palmerj** [comment]
@springmeyer: Thanks so much for looking at this! Issue make sense. Thanks for the initial mapnik patch.

In regards to tilemill, is a new release due soon?

**Comment by springmeyer** [comment]
@palmerj - yes, I'm working hard right now on an official Mapnik 3.0.0 release. And new node-mapnik release to use it. After that I'll move to update TileMill to Mapnik 3.0.0, make sure it works, and then plan to issue a new TileMill release. mapnik/mapnik#2902 is not yet fixed, but hope to get to it in the next week(s). Hopefully you are okay for now using your same current tilemill and `scaling="near"`? If that is too jaggy you could try `direct-image-filters:agg-stack-blur(1,1);` to smooth the resulting raster a little big. Of course blurring is not what you ideally want, but might be a decent stopgap until mapnik/mapnik#2902 is fixed. Let me know.

**Comment by palmerj** [comment]
@springmeyer: Thanks heaps - sound like a good plan. Can't wait for Mapnik 3.0. Let me know if you need any help testing anything.

**Comment by Komzpa** [comment]
closing as it's not Tilemill codebase issue.
