### ISSUE TITLE
unable to reach the local TileMill Server

### ISSUE THREAD

**Issue by jhgdike** [tilemill-project/tilemill#2516]
Unable to reach the local TileMill Server. Check the logs for details. If this problem persists please contact support at: http://support.mapbox.com/discussions/tilemill

Unable to download 'http://mapbox-geodata.s3.amazonaws.com/natural-earth-1.4.0/cultural/10m-admin-0-countries.zip' for 'countries' (getaddrinfo ENOENT)

**Comment by springmeyer** [comment]
Hi there, this is happening likely just due to a network problem. It will likely work if you try it a second time.

**Comment by jhgdike** [comment]
I have tried it for 5 or more times, but it still  doesn't work. Maybe it's my network's fault, I will try it later. Thank you!
