### ISSUE TITLE
Export to PDF/SVG failed in Windows

### ISSUE THREAD

**Issue by mappymapmap** [tilemill-project/tilemill#2518]
Mornin'

I have Windows 8 and I am using the most recent version of Tilemill available from the website.

I have a map with a few thousand points rendered as shapefiles in OpenJump, some road lines downloaded from the Canadian census website, and shapefiles outlining Canada's FSAs. I got rid of all zoom options and I just want to print a PDF of my map : (

Around half the time, I am able to export a PDF with no text rendered. But currently, neither the PDF nor the SVG options work.

Tilemill simply tells me "Export process failed (see tilemill log for details)" and the error log is as follows:

[tilemill] [tilemill-ui] [millstone] processing style 'style.mss'
[tilemill] [tilemill-ui] [millstone] processing layer 'area'
[tilemill] [tilemill-ui] [millstone] processing layer 'roads'
[tilemill] [tilemill-ui] [millstone] processing layer 'one_50'
[tilemill] [tilemill-ui] [millstone] processing layer 'three_50'
[tilemill] [tilemill-ui] [millstone] processing layer 'two_50'
[tilemill] [tilemill-ui] [millstone] processing layer 'cities'
[tilemill] [tilemill-ui] [millstone] finished processing ' my file location + name and stuff '
[tilemill] Export process failed
[tilemill] [tilemill] no crash logs found

Any help would be appreciated!

**Comment by springmeyer** [comment]
try installing the windows dev build linked from https://github.com/mapbox/tilemill/issues/2081#issuecomment-25582979 and let us know if that fixes the export with text.

**Comment by Snowrotberg** [comment]
I have the same problem, but he link dosn't work anymore :)

**Comment by csytsma** [comment]
Try: http://tilemill.s3.amazonaws.com/index.html
