### ISSUE TITLE
Cannot convert null to object

### ISSUE THREAD

**Issue by springmeyer** [tilemill-project/tilemill#2519]
Hit this with the OS X build from https://gist.github.com/bsudekum/b4606871250d9d834b3d#file-tm-md.

```
[tilemill] TypeError: Cannot convert null to object
[tilemill]     at Function.<anonymous> (/Users/dane/Downloads/tilemill-darwin-x64-atom/TileMill.app/Contents/Resources/app/node_modules/tilelive-mapnik/lib/mapnik_backend.js:358:16)
[tilemill]     at /Users/dane/Downloads/tilemill-darwin-x64-atom/TileMill.app/Contents/Resources/app/node_modules/tilelive-mapnik/lib/lockingcache.js:72:26
[tilemill]     at Array.forEach (native)
[tilemill]     at LockingCache.<anonymous> (/Users/dane/Downloads/tilemill-darwin-x64-atom/TileMill.app/Contents/Resources/app/node_modules/tilelive-mapnik/lib/lockingcache.js:71:23)
[tilemill]     at process._tickDomainCallback (node.js:463:13)

```

**Comment by springmeyer** [comment]
hit this consistently with the `geography class` built in map. I think the next step is to just update deps (by pulling lastest master into atom branch) and see if it goes away.

**Comment by springmeyer** [comment]
happening on https://github.com/mapbox/tilelive-mapnik/blob/master/lib/mapnik_backend.js#L359. This may be some kind of mismatch in tilelive.js version as well.

**Comment by christianbundy** [comment]
@springmeyer any chance you got this resolved? Currently banging my head against the wall with this issue.
