### ISSUE TITLE
Canadian highway .svg rendering weird

### ISSUE THREAD

**Issue by mappymapmap** [tilemill-project/tilemill#2521]
Hi,

I downloaded various Canadian highway .svg files from Wikipedia. I am trying to use them as markers for the highway on my map.

The .svg file looks file when I open it, but when I link to it on my map, all the numbers are skewed right while the highway sign itself looks fine.

Any ideas on why the .svg file is rendering differently in tilemill?

**Comment by Komzpa** [comment]
Tilemill uses http://mapnik.org/ to render the map. Likely it is a font matching issue in Mapnik. Vectorize your icons not to have text elements, and it should become much better.
