### ISSUE TITLE
ECONNRESET - openstreetmap-carto style

### ISSUE THREAD

**Issue by GravitaZ** [tilemill-project/tilemill#2526]
I am trying to load the openstreetmap-carto style for the southeast US
I am having some odd issues, sometimes it works and loads great, sometimes it loads the layers very slowly, but most of the time I receive this error.
http://i.imgur.com/e8dW7fd.jpg
I have seen some of the similar errors and set the cursor_size, but it didn't seem to help.
"advanced": {
        "cursor_size": 10000
      }
    },
I am using postgreSQL 9.2

**Comment by Komzpa** [comment]
sorry, not actionable without context. would you please try again with new tilemill from master and open another issue if problem persists?
