### ISSUE TITLE
Error: Project does not exist

### ISSUE THREAD

**Issue by SITUResearch** [tilemill-project/tilemill#2535]
![tilemill_error](https://cloud.githubusercontent.com/assets/14979995/10352622/4016bb8a-6d1e-11e5-8e57-80ba363f3a3d.JPG)

I was also having an issue just displaying the raster properly.

**Comment by Komzpa** [comment]
sorry, not actionable without context. would you please try again with new tilemill from master and open another issue if problem persists?
