### ISSUE TITLE
Error reported on valid file names

### ISSUE THREAD

**Issue by tadiraman** [tilemill-project/tilemill#2546]
See here for the error:
Error: Filename may include alphanumeric characters, 
dashes and underscores.
![tilemill](https://cloud.githubusercontent.com/assets/1202458/13645450/0bf97438-e5f9-11e5-8940-4ffa4d172a4d.png)

**Comment by Komzpa** [comment]
sorry, not actionable without context. would you please try again with new tilemill from master and open another issue if problem persists?
