### ISSUE TITLE
Tooltips no longer working

### ISSUE THREAD

**Issue by Caucasus-and-Mercury** [tilemill-project/tilemill#2547]
Hi there,

I downloaded the latest release from http://tilemill.s3.amazonaws.com/index.html, dated Sun Mar 06, and tooltips are no longer working. The functionality is just gone, nothing.

As for legends I haven't checked.

Edit: I should add that this is an issue with the uploaded tiles accessed with for example mapbox.js. In the Tilemill interface everything is normal.

**Comment by springmeyer** [comment]
hmm, it may be what I fixed in https://github.com/mapbox/tilemill/commit/671bd0079d05cf7378cc69041ad93da8d9a1cfd9 and then forgot about...

**Comment by ecodiv** [comment]
I am having the same problems (running version 0.10.2 (v0.10.1-400-g9d4a9b9) on Linux). At export, no json files (utfgrid) are generated. Or if they are, they are not created when using mb-utils to convert the mbtiles file to folder with tiles.

**Comment by bmcbride** [comment]
Is there currently any workaround to get tooltips working on the latest version?

**Comment by ecodiv** [comment]
Try Tileoven (fork of tilemill) , that may work better (done a quick test, 
and seems to work, at least the mbtiles created contained utfgrid)

**Comment by bmcbride** [comment]
@ecodiv: Thanks! I was able to install without any issues on OS X El Capitan and it works great!

**Comment by Komzpa** [comment]
@bmcbride @ecodiv @maxmeles  could you please help with merging Tileoven updates back to Tilemill?
join discussion https://github.com/florianf/tileoven/issues/5 for details.

**Comment by florianf** [comment]
@Komzpa I think the reason why it works in tileoven is because I never updated tilelive. The continue unfinished Export feature was also dropped due the update, that's why i didn't update.

**Comment by jmuchaxo** [comment]
Any updates on this? I generated again tiles for an old project from 2014 and with latest tilemill 0.10.2 it does not generate the interaction grids anymore

**Comment by csytsma** [comment]
Fixed in TileOven, prior to merge back into TileMill.
