### ISSUE TITLE
Tile is not defined... in tilemill export

### ISSUE THREAD

**Issue by emacgillavry** [tilemill-project/tilemill#2559]
Running the export command, the process died unexpectedly. Running Ubuntu 14.04 with fresh clone of TileMill. Postgres is running on the same server.

[0s] Part(1/1) 17.1053%Export process died: ReferenceError: tile is not defined
    at Scanline.<anonymous> (/usr/local/src/tilemill/commands/export.bones:519:43)
    at Scanline.EventEmitter.emit (events.js:95:17)
    at /usr/local/src/tilemill/node_modules/tilelive/lib/stream-scanline.js:105:24
    at /usr/local/src/tilemill/node_modules/tilelive/lib/stream-util.js:262:22
    at Function.<anonymous> (/usr/local/src/tilemill/node_modules/tilelive-mapnik/lib/mapnik_backend.js:330:25)
    at /usr/local/src/tilemill/node_modules/tilelive-mapnik/lib/lockingcache.js:72:26
    at Array.forEach (native)
    at LockingCache.<anonymous> (/usr/local/src/tilemill/node_modules/tilelive-mapnik/lib/lockingcache.js:71:23)
    at process._tickDomainCallback (node.js:463:13)
Exiting process [tm-buildings.mbtiles]

**Comment by emacgillavry** [comment]
Upping the `connect_timeout` parameter in the MML file seems to address the problem.

**Comment by emacgillavry** [comment]
Hitting same wall again. Zoom level 8 or 9 (one at a time) for just NL works, but supplying 8 through to 18 fails. Now setting concurrency to 1?

**Comment by emacgillavry** [comment]
`concurrency=1` and `scheme=pyramid` seems to work nicely. Now leaving out `concurrency` again, while maintaining `scheme=pyramid`.

**Comment by F3L1X79** [comment]
I hit the same problem with concurrency=24. Maybe this is due to that. I'll try with concurrency=1 and scheme=pyramid, but I guess the export will be hours and hours longer in that case?

**Comment by F3L1X79** [comment]
OK! The bug is due to this line 518 in /commands/export.bones:
```
        function writeTiles() {
            get.on('error', function(err, tile) {
				console.warn('\r\033[K' + tile.toString() + ': ' + err.message);
				fs.write(fd, JSON.stringify(tile) + '\n');
				//report(task.stats.snapshot());
            })
```;
A coma is missing between error and tile...

**Comment by azizul-bkash** [comment]
I am facing the same issue currently. Did anyone solved this?

**Comment by F3L1X79** [comment]
@azizul-bkash Didn't my answer help?

**Comment by azizul-bkash** [comment]
Can I see my logs?

**Comment by F3L1X79** [comment]
Oh yes you can.

**Comment by azizul-bkash** [comment]
Sorry, I meant, How can I see my logs?

**Comment by F3L1X79** [comment]
You launch the command with **--verbose=on**

After editing the function in `/commands/export.bones` line 518 of your tilemill install folder like this:
```
function writeTiles() {
     get.on('error', function(err) {
	console.warn('\r\033[K' + ': ' + err.message);
	//fs.write(fd, JSON.stringify(tile) + '\n');
	//report(task.stats.snapshot());
    });
```

**Comment by azizul-bkash** [comment]
After performing your instruction......the export running but it returns few error messages

```
: Postgis Plugin: FATAL:  remaining connection slots are reserved for non-replication superuser connections
Connection string: 'host=localhost port=5432 dbname=osm user=admin connect_timeout=4'
```

**Comment by F3L1X79** [comment]
So it's not a TileMill issue. I'm too bad at Postgis, so I can't help you on this.

**Comment by csytsma** [comment]
Appears to have been fixed in TileOven, prior to merge back into TileMill.
