### ISSUE TITLE
Sits at loading screen on OSX

### ISSUE THREAD

**Issue by dhalyk** [tilemill-project/tilemill#2569]
I wanted to try out TillMill and I have a new 5K iMac 32GB ram and lots free and when I try to start TillMilll it just sits at the loading screen. I have tried waiting for over 20 minutes but nothing.

Any ideas?

![image](https://cloud.githubusercontent.com/assets/1850840/17640691/64c101f8-60d3-11e6-8490-6da90d656b3c.png)

**Comment by tmcw** [comment]
Duplicate of #2539
