### ISSUE TITLE
file could not be found:

### ISSUE THREAD

**Issue by Loubnabarra** [tilemill-project/tilemill#2570]
Can you help me please, i want to add (picture.jpg) to specific polygon from a links to be a symbol of spesifik build. I do this: 
[toponyme = 'Police']{ 
polygon-fill: "url":"C:\Temp\loubna-terrain\terrain-sport.jpg";
 }
and i receive this answer:
Failed to parse expression: "X:\loubna-test\TileMill\police.png" in style 'batiments_labels' in PolygonSymbolizer.
How to do? please can some one helpe me, thank you.

**Comment by tmcw** [comment]
Try

```
[toponyme = 'Police']{ 
polygon-fill: "C:\Temp\loubna-terrain\terrain-sport.jpg";
}
```

The `"url":` syntax here is invalid, and doesn't appear, as far as I know, in any CartoCSS documentation or examples.

**Comment by Loubnabarra** [comment]
tahnk you for your response.
It doesn't work, I change the place but it still doesn't work :
[toponyme = 'Police']{ 
   polygon-fill: "C:\tilemill\police.png";

Failed to parse expression: "C:\tilemill\police.png" in style 'batiments_labels' in PolygonSymbolizer.

please help me I don't know what to do. Thank you for your respens.

**Comment by BergWerkGIS** [comment]
Haven't check myself but maybe `/` instead of `\` could solve this?

```
"C:/tilemill/police.png" => "C:/tilemill/police.png"
```

**Comment by Loubnabarra** [comment]
I tray it, it doesn't make me any error but I don't see de symbol, no change!!!!!

**Comment by Loubnabarra** [comment]
It Work with marker-file and with link from net:
   [toponyme = 'Parking']{ 
   marker-file: url('http://www.regentpalacehotel.co.uk/images.jpg');
   marker-width: 15.0;
   }
But I still not understanding why it doesn't work with local link:
[toponyme = 'Parking']{
marker-file : url("C:/tilemill/police.png");
marker-width: 15.0;
   }
Thank you BergWerkGIS and tmcw for your help.

**Comment by BergWerkGIS** [comment]
@Loubnabarra probably you got the wrong filename/path or a permission problem.

All these variations work for me:

```
marker-file: url('C:/mb/_TEMP/images.jpg');
```

```
marker-file: url('C:\mb\_TEMP\images.jpg');
```

```
marker-file: url('/mb/_TEMP/images.jpg');
```

![image](https://cloud.githubusercontent.com/assets/4549888/17996340/aff5ed62-6b57-11e6-8ebc-b48bfcd0b299.png)

**Comment by Loubnabarra** [comment]
Hallo @BergWerkGIS, I need your help if you want.
I want to add the road arrows in the good direction of the road  like this following map:
https://travel.sygic.com/#/?map=18,55.94719,-3.19154&type=poi
on the other case, I would like to update our basemap, but I don't know what  can I add like new think, so I m allow to ask your help, what will you propose me to do for adding new valeu on this basemap.
I wold thank you for your help and for your idea.
basemap: http://map.geoportail.lu
