### ISSUE TITLE
Map style strange overriding

### ISSUE THREAD

**Issue by edpop** [tilemill-project/tilemill#2572]
Hello.

```
Map {
  background-color: @blue;
}
Map {
  background-color: @green;
}
```
If i do this style in one file, the *background color* will be **blue**. If i split these styles in different files, the color will be a last defined, as expected in css-like formats.

At the second - conditions are not working on **Map** :(
```
Map [zoom > 10] {
  background-color: @green;
}
```

**Comment by Komzpa** [comment]
Hi,
would you please report this issue to Carto language repository?
https://github.com/mapbox/carto

Thanks!
