### ISSUE TITLE
Can't export to MBTile v0.10.2

### ISSUE THREAD

**Issue by Juko** [tilemill-project/tilemill#2581]
Using the pre release v0.10.2 version found in another issue solving the problem of the infinite loading screen on El Capitan 10.11.4.

When I go to export as an MBTile, it gives a progress bar of exporting, then it gets stuck on 0 seconds remaining (it never changes to the save button). The file then continuously inflates in size over time, and there's still a notification icon on TileMill when switching apps (in cmd + tab) even if I delete the export.

Version 0.10.1 gets stuck when trying to load font files, so I can't downgrade to that version even though it is able to export a map without font files.

**Comment by MobileAndyB** [comment]
Just seconding this. The mbtiles files grow until they are 27.8mb and i think the tiles created seem to be around the centre point not the bound that have been set.

**Comment by csytsma** [comment]
Fixed in TileOven, prior to merge back into TileMill.
