### ISSUE TITLE
[tilemill] Error: child process : "tile failed with error code 3, Exporting Large KML to MBTiles - error messege and crash

### ISSUE THREAD

**Issue by OisinSlevin** [tilemill-project/tilemill#2582]
Hi guys,
I have large KMLs im trying to convert to mbtiles, the software crashes, either while loading up the KML, or during export, I'm getting the feeling it cant handle kmls of 100mb any solutions

**Comment by Komzpa** [comment]
@OisinSlevin can you transform your KML into ESRI Shapefiles using ogr2ogr and retry with those?

**Comment by csytsma** [comment]
Please re-open if still an issue.
