### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pcoder** [tilemill-project/tilemill#2587]
When I try to export a tilemill project using the following command,

`node ./index.js export "myproject" --format=mbtiles --bbox="-5.625,39.5040,13.0078,52.1605" --minzoom=0 --maxzoom=15 --metatile=16`

I get the following error
```
util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded
```

To give you more idea about the project, I have around 200,000 points in the given bounding box.

I am using the following version of tilemill on Fedora 23, with 8GB of ram and i7-4600U CPU @ 2.10GHz processor.
```
Version 0.10.2 (v0.10.1-412-g2251a6d)
Copyright © 2010-2014 Mapbox, Inc.
```

I have tried increasing the call stack size using `ulimit -s`, but the results yield a segmentation fault after 30 minutes of execution. 

Is there any workaround for this? 

Thanks in advance and highly appreciate any response.

**Comment by Komzpa** [comment]
Closed for the same reason https://github.com/florianf/tileoven/issues/9 is closed.
