### ISSUE TITLE
Allow variables to be set within conditional sections

### ISSUE THREAD

**Issue by csytsma** [tilemill-project/tilemill#2590]
It appears that variables can only be set as a stand-alone line.  For example:
`@color:  red;`

It would be great if the variable assignment could happen within a conditional, so the value could be set based upon the element being rendered.  For example, with [name] being set in the layer data:

`[name='trek']  { @color: red;  }`
`[name='bike'] { @color: blue; }`
`[name='canoe'] { @color: green; }`
`line-color: @color;`

**Comment by Komzpa** [comment]
@csytsma this should be reported towards https://github.com/mapbox/carto.

**Comment by csytsma** [comment]
Created https://github.com/mapbox/carto/issues/461
