### ISSUE TITLE
Cast a variable to Float

### ISSUE THREAD

**Issue by csytsma** [tilemill-project/tilemill#2597]
It would be great if it was possible in the CartoCSS language in Tilemill to be able to cast a variable to float, so it can be used in styles that require a Float.

For example, I use JOSM to create a set of Points that have meta data associated to them, and then pull that file into Tilemill to display them as labeled points: circles with a label on them.  I'd like to be able to specify in JOSM the DX and DY offsets for displaying the label.  However, when I set a DX and DY value and pull it into Tilemill, it comes in as a String. But the text-dx and text-dy style elements are expecting a Float.

I haven't been able to find a way to cast the file variable to Float. If there is, I'd love to hear how.

Otherwise, would be great to add this functionality.  Either explicity with a 'cast' type command, or just by doing a math operation, such as:
`text-dx: [dx]*1.0;`

**Comment by pnorman** [comment]
I think this should be raised against Mapnik, not [CartoCSS](https://github.com/mapbox/carto).

Mapnik does support multiple types of variables, but the osm input plugin probably doesn't.
