### ISSUE TITLE
One part of map disappears when zooming, no zoom filters set

### ISSUE THREAD

**Issue by catherinetucker** [tilemill-project/tilemill#2605]
I have 4 groups (A,B,C,D) which all appear at zoom level 0-7. However, suddenly at zoom 8, group D suddenly disappears from the map. The rest of the groups still appears at zoom 8, it's just group D.

**Comment by csytsma** [comment]
I experience the same thing, and also see it when I export a map.  I only notice it for one Layer though, which is an .osm file which I use to plot Circles and Text Labels.  Just some of the elements won't display.

I see this for PDF and MBTile exports.  When viewing a MBTile, I'll see the same behavior as I change zoom levels, certain elements from that same layer disappear.

MacOS, Tilemill v0.10.1-291-g31027ed
OSM Bright base project, with lots of styling changes, and additional layers
Layer is an .osm file exported from JOSM.

**Comment by csytsma** [comment]
This appears to only happen to .osm layers. As they are no longer supported, this bug is no longer relevant.
