### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by donohoe** [tilemill-project/tilemill#2616]
In following steps on this page to add a Earthquake layer:

http://tilemill-project.github.io/tilemill/docs/crashcourse/point-data/

It says to add this:

_7. Enter the URL http://earthquake.usgs.gov/earthquakes/feed/csv/2.5/week into the “Datasource” field._

The app gives me this error:

`Unable to download 'http://earthquake.usgs.gov/earthquakes/feed/csv/2.5/week' for 'earthquakes' (server returned 404)`

**Comment by csytsma** [comment]
That csv file doesn't appear to be on the USGS server anymore. I'd suggest looking for the file on their website and use the new URL.

Ok, just doing a quick 30 second look on their website found the file:
https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.csv <https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.csv>

Or any other time frame:
https://earthquake.usgs.gov/earthquakes/feed/v1.0/csv.php <https://earthquake.usgs.gov/earthquakes/feed/v1.0/csv.php>

-Cory

**Comment by csytsma** [comment]
Updated with correct link.
