### ISSUE TITLE
Issue Creating New Stylesheet

### ISSUE THREAD

**Issue by isaacnk** [tilemill-project/tilemill#2625]
Tilemill v0.10.1-291-g31027ed on 2016 13-inch MacBook Pro running OSX 10.13.4 
Whenever attempting to create a new stylesheet with the plus icon on the editor, Tilemill exits project and displays message: "Error: Page not found". Unable to create new stylesheet without running into this issue.

**Comment by csytsma** [comment]
As a temporary workaround you can manually create a new .mss file for your tab in your specific project folder. 

-Cory
