### ISSUE TITLE
Text/marker overlap - only overlap other layers, but not other objects on the same layer

### ISSUE THREAD

**Issue by dannyuk1982** [tilemill-project/tilemill#2627]
Hi all, anyone know how to action this, or can functionality be added?

I basically have this issue: https://gis.stackexchange.com/questions/220890/mapnik-cartocss-make-text-labels-overlap-other-layers-but-not-each-other

I have a couple of layers (subways stations being one) where I need the labels/markers to not overlap each other (but *only* for this later), otherwise there e.g. are 4-5 exits for a station and it's unreadable as they all overlap. However, they DO need to overlap (or at least always take priority) over other laters such as road names and area names. Even with the e.g. subway layer being on top, with the style for its markers/text declared before anything, things like area names stop it being rendered sometimes.

The workaround in that link is to pass MapNik `clear-label-cache="on"`, I have tried this as a string in `project.mml` and also a JSON object. I can't do within the TileMill GUI as setting anything in the advanced box gives an `Error: Page no found`

**Comment by csytsma** [comment]
In regard to passing Mapnik options, have you tried exporting to XML, then manually editing the XML file?  Tilemill will supposedly then use that XML file the next time you export.

http://tilemill-project.github.io/tilemill/docs/manual/exporting/#mapnik-xml-export <http://tilemill-project.github.io/tilemill/docs/manual/exporting/#mapnik-xml-export>

**Comment by dannyuk1982** [comment]
Hey @csytsma, that actually works great, nice one! So I ended up with:

```
<Layer name="stations" clear-label-cache="on"
```
