### ISSUE TITLE
Japanese Label

### ISSUE THREAD

**Issue by peppemath** [tilemill-project/tilemill#2629]
Ciao
I need to create a mbtiles file to use offline because there is no internet connection.
The area that interests me is Japan: I downloaded the .shp files from geofabrik and imported some layers in my project, in particular I would like to display the names of the cities. The problem is that Japanese characters are displayed with small squares. How can I display Japanese glyphs on labels? Can someone give me a hand ??
Thanks!

![japan_tilemill_label_problem](https://user-images.githubusercontent.com/43339121/45619602-30110b80-ba7a-11e8-9dda-6a915e337a37.png)

**Comment by csytsma** [comment]
This would most likely be a Font issue. Make sure your font can handle Unicode.  I quickly uploaded a portion of Japan into my Tilemill and it displayed the Japanese glyphs correctly (this is on a Mac).

My Tilemill is setup to use:
`@sans:              "Open Sans Regular","DejaVu Sans Book","unifont Medium";
`

You could also try using the Japanese font Hiragana instead.

**Comment by csytsma** [comment]
A little more reading on this topic...
https://github.com/tilemill-project/tilemill/issues/2138

**Comment by peppemath** [comment]
> This would most likely be a Font issue. Make sure your font can handle Unicode. I quickly uploaded a portion of Japan into my Tilemill and it displayed the Japanese glyphs correctly (this is on a Mac).
> 
> My Tilemill is setup to use:
> `@sans: "Open Sans Regular","DejaVu Sans Book","unifont Medium";`
> 
> You could also try using the Japanese font Hiragana instead.
> 
> I changed my Tilemill to use "Arial Regular" and I got the boxes instead of the glyphs.

It works!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
GRAZIE!!!!!!!!!!!!!!
