### ISSUE TITLE
Update Mapnik to use v3.7.2?

### ISSUE THREAD

**Issue by IReese** [tilemill-project/tilemill#2636]
I opened this issue: https://github.com/tilemill-project/tilemill/issues/2635 in order to explore errors we were getting when trying to open large rasters in Tilemill.  We solved it by updating the Mapnik version to 3.7.2 in the `package.json` before installation.

Is this an update useful in the repo?

**Comment by csytsma** [comment]
Implemented.

**Comment by IReese** [comment]
@csytsma Thank you!
