### ISSUE TITLE
TileMill in server mode, quick crash. Excepted in `npm test`

### ISSUE THREAD

**Issue by 7tonin** [tilemill-project/tilemill#2684]
Hi,
On one hand, TileMill run from command line crashes very quickly: `./tilemill.sh`. 
```
[tilemill] Starting in server mode.
[tilemill] url.js:314
[tilemill]       this.hostname = toASCII(this.hostname);
[tilemill]                       ^
[tilemill] 
[tilemill] Error: Cannot convert name to ASCII
[tilemill]     at Error (native)
[tilemill]     at Url.parse (url.js:314:23)
[tilemill]     .../... etc
```
[npm-debug-20190228-1545.log](https://github.com/tilemill-project/tilemill/files/2915496/npm-debug-20190228-1545.log)

On the other hand, when running `npm test`, it's long enough, about 10 min, to let me discover a bit TileMill on my browser through localhost:20009

How to solve this ?

**Comment by csytsma** [comment]
@7tonin what OS are you running? 
It looks like you are using node@v6.10.3. Can you please try using node lts/carbon? (see README)
What steps did you go through to install this latest version of TileMill?

**Comment by 7tonin** [comment]
##### OS is linux Mageia 6 (4.14.100-desktop-1.mga6).

##### To install TileMill, I downloaded it, 
```
cd ~/logiciels/
git clone https://github.com/tilemill-project/tilemill.git
```
```
npm install
npm install mocha
npm test
```
Installed pgsql 9.6.10 from packages
and compiled postgis-2.5.2dev from sources, then installed
At this point, things started to run ok. _Almost_.

##### Moving to LTS/Carbon
I uninstalled too old packaged nodejs and npm, then succeeded in compiling and install nodejs:
```
$ npm -v
6.4.1
$ node -v
v6.10.3
```
re-run
```
npm install
npm install mocha
npm test
```
Now it looks worse (!)
I'm facing node_modules install problem, like with mapnik `# npm install -g mapnik`.
Don't really now where to go, is it only feasible ? Looking toward Mageia7 RC...

**Comment by 7tonin** [comment]
Oupsss !
```
$ node -v
v8.15.1
```

**Comment by 7tonin** [comment]
On Mageia 7, node@10.14.2 is too recent for requested mapnik@3.7.2
[installation_TileMill-mga7.txt](https://github.com/tilemill-project/tilemill/files/2918967/installation_TileMill-mga7.txt)

**Comment by 7tonin** [comment]
Finally installed ubuntu-14.04.4-server-amd64.iso in a VirtualBox.
Did install TileMill  v0.10.1 (according to https://tilemill-project.github.io/tilemill/docs/linux-install/)
Set up my ubuntu vbox network visibility from my host with video tutorial _VirtualBox host-only network on Ubuntu Server 14_ https://www.youtube.com/watch?v=AXgytCOZ6c8
(May help too _VBox manual ch6.7 Host-Only Networking_ https://www.virtualbox.org/manual/ch06.html#network_hostonly)
