### ISSUE TITLE
Running TileMill as Ubuntu service doesn't correctly serve Tiles

### ISSUE THREAD

**Issue by Rolinenik** [tilemill-project/tilemill#2688]
I'm trying to deploy a new tilemill server on Ubuntu 18.04 and could not start the server right.
With ./index.js --server=true --listenHost=0.0.0.0 I get following output (other arguments also with setting in config.json have the same result):

Note: Unknown option "server".
Note: Unknown option "listenHost".
[tilemill] Starting in server mode.
[tilemill] Note: Unknown option "server".
[tilemill] Note: Unknown option "server".
[tilemill] Note: Unknown option "listenHost".
[tilemill] Started [Server Tile:20008].
[tilemill] Plugin [carto] loaded.
[tilemill] Plugin [editor] loaded.
[tilemill] Plugin [fonts] loaded.
[tilemill] Plugin [templates] loaded.
[tilemill] Started [Server Core:20009].

There isn't written a logfile (tilemill.log) anywhere on the system. Access to web ui is possible but all projects havn't any thumbnails and opening a project results in maps without content in the tiles. No rendering process ist running.

Environment:
- Ubuntu 18.04, nvm 6.8.0, node 8.11.3, 
- postgresql 11, 
- tilemill 1.0.1 from github, openstreetmap-carto 4.20.0 from github

Where can I look for root cause or more detailed view of a probalbly bug?

**Comment by csytsma** [comment]
With the new version, it only runs in Server mode on localhost.  Try just running 'npm start'.

I spun up a new VM yesterday with Ubuntu 18.04, no parameters, and it started correctly and I was able to connect on 127.0.0.1:20009.

Unfortunately, the current logging is pretty poor. That's on the list, to improve debug logging.

-Cory

**Comment by Rolinenik** [comment]
That explains my failure. Is it planned to make remote access via web ui usable again in a future release?
Currently I want to run tilemill on a ubuntu server, without gui. The additional installation of a gui and remote access to it is quite cumbersome.

**Comment by csytsma** [comment]
The only way to run the latest v1.0.x version is with remote access via web browser ui.  There is no additional GUI.

When you start TileMill with 'npm start' or './index.js', then open your web browser and go to http://127.0.0.1:20009, do you get the same problems?  Did you wait long enough for it to cache all remote resources?  

You can try to turn on an additional level of logging in your local config file ~/.tilemill/config.json:
	"verbose": "on"

**Comment by Rolinenik** [comment]
Now I am confused. For me, remote access means accessing from another computer: http://127.0.0.1:20009 is therefore local access. This works on my system (but I just need a local gui like kne/gnome or similar on this system, then start a web browser and go to the localhost:20009 address.)

If I have understood you correctly, tilemill cannot currently listen to an address other than 127.0.0.1/localhost. Is the functionality planned again in a future release?

**Comment by csytsma** [comment]
@Rolinenik I tested running TileMill v1.0.1 as a remote service today, and appears to be working correctly.  Here's my configuration and setup. Please correct me if this is the incorrect use case. The error messages when starting can be disregarded.

Ubuntu 18.04.02, Node v8.15.1, TileMill v1.0.1, IP: 10.0.0.98
`./index.js --server=true --listenHost=0.0.0.0 --coreUrl=10.0.0.98:20009 --tileUrl=10.0.0.98:20008`

Note: Unknown option "server".
Note: Unknown option "listenHost".
Note: Unknown option "tileUrl".
[tilemill] Starting in server mode.
[tilemill] Note: Unknown option "server".
[tilemill] Note: Unknown option "listenHost".
[tilemill] Note: Unknown option "coreUrl".
[tilemill] Note: Unknown option "tileUrl".
[tilemill] Started [Server Tile:20008].
[tilemill] Note: Unknown option "server".
[tilemill] Plugin [carto] loaded.
[tilemill] Plugin [editor] loaded.
[tilemill] Plugin [fonts] loaded.
[tilemill] Plugin [templates] loaded.
[tilemill] Started [Server Core:20009].

In my browser on a Mac on the same internal network, I entered:
`http://10.0.0.98:20009`

I was able to successfully connect to the running instance of TileMill and view/edit Projects, and map tiles displayed correctly.

I suspect that you didn't specify the coreUrl and tileUrl parameters, which will results in the tiles not being served up correctly.

Can you test this same setup and report back?

**Comment by csytsma** [comment]
@amenk Thanks for the additional confirmation.  The incorrect error messages were fixed with issue #2685 and was merged into dev branch. It will be released with v1.0.2.

Closing this issue as fixed.
