### ISSUE TITLE
Tutorial doesn't work: "Could not create datasource for type: 'csv'"

### ISSUE THREAD

**Issue by Aruee** [tilemill-project/tilemill#2696]
Could not create datasource for type: 'csv' (searched for datasource plugins in '/home/username/Quellcode/thirdParty/tilemill/node_modules/mapnik/lib/binding/lib/mapnik/input')

I get this when trying to load .csv files as a datasource. While I'm sure that this might be easy to fix with a little tinkering, I'm getting this while I'm going through the very basic tutorial at https://tilemill-project.github.io/tilemill/docs/crashcourse/point-data/. I just guess that it's not supposed to happen. I'm trying to go through the tutorial on a RedHat machine, if that might be an issue.

Unrelated but relevant: I needed to pick my own .csv files because the tutorial-referenced URL http://earthquake.usgs.gov/earthquakes/feed/csv/2.5/week (which is supposed to host the csv data) seems to be dead (at least the browser just showed me a 404 when I open the URL).

**Comment by csytsma** [comment]
Jannis,

Can you share how you installed TileMill, and version? What is the version of Node you are using?

It sounds like you’re TileMill is using an incorrect version of Mapnik. 

Thanks for reporting bad link on csv. 

-Cory

**Comment by csytsma** [comment]
Closing as no response. Please open if you have more information.
