### ISSUE TITLE
cartodb base-light style

### ISSUE THREAD

**Issue by pedro-vicente** [tilemill-project/tilemill#2714]
I would like to define the "base-light" style 

https://github.com/CartoDB/cartodb/wiki/BaseMaps-available

of cartoDB

https://github.com/CartoDB/CartoDB-basemaps

in TileMill.
How could this be done?

example of the style (polygons not part of style, made with Wt , https://github.com/pedro-vicente/wt)

http://www.eden-earth.org:8082/

**Comment by csytsma** [comment]
@pedro-vicente It seems you'd need to convert the CartoDB style to the TileMill style. Without seeing their style file, it's hard to provide any input.

Can you post the desired style file, and we can take a look and advise on the differences?  I'm assuming you ran `node create_named.js positron-all.yml light_all` and have the output file?

**Comment by csytsma** [comment]
Closing since no response. Please re-open if you have more data to report.
