### ISSUE TITLE
Link to sample shape files results in Error 404

### ISSUE THREAD

**Issue by davidkneely** [tilemill-project/tilemill#2723]
**Describe the bug**

On this page: https://tilemill-project.github.io/tilemill/docs/guides/osm-bright-mac-quickstart/

These links do not work:

wget http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip
wget http://data.openstreetmapdata.com/land-polygons-split-3857.zip

I want to download these files to complete the tutorial on the page.

Please advise,

David

**Environment: (Note: We are not setup to test on Linux or Windows so help may be slower on those OSs)**
 - OS & Version: [e.g. MacOS Mojave]
 - Browser & Version: [e.g. Safari 12.0.3]
 - Node Version [e.g. v8.15.0] (you can type nvm version at a terminal prompt to find this)

**To Reproduce**

**Expected behavior**

**Installation Method**
If this is a problem installing or running TileMill after an installation, please describe the method you used to install TileMill.

**Screenshots and logfile**
If applicable, add screenshots or a copy of your terminal output to help explain your problem.

**Additional context**

**Comment by csytsma** [comment]
Updated polygon sample file links.

**Comment by Firefishy** [comment]
New URLS:
https://osmdata.openstreetmap.de/download/simplified-land-polygons-complete-3857.zip
https://osmdata.openstreetmap.de/download/land-polygons-split-3857.zip

The old domain registration lapsed.

**Comment by Firefishy** [comment]
Ah ignore me ;-)
