### ISSUE TITLE
MBTiles Export does't work with tileserver

### ISSUE THREAD

**Issue by BenjaminQuandt** [tilemill-project/tilemill#2726]
**Describe the bug**
I used tilemill with openstreetmap-carto to get a MBTiles export that I can use with a tileserver. In Tilemill the Map looks correct. Also my exported MBTiles file don't look that wrong. If I put the file into the tileserver I can select the map but I can't see anything on it. If I take the file from Mapbox, the tileserver will show a map. It looks like my export file is broken. But if i extract it, I get a folder/picture structure that looks good for me.

**My Versions**
 - Ubuntu 18.04
 - Node Version v8.16.1
 - "sqlite3": "4.0.6"

**Expected behavior**
- Add everything I need to a Project.
- use Export with: `node index.js export project_folder ~/export_path/filename.mbtiles --format=mbtiles --log=log_path --files=MapBox_folder `
- use file in tileserver

**Installation Method**
- followed the readme

**Additional context**
- The tileserver I use: https://hub.docker.com/r/klokantech/tileserver-gl/
- The referance file that works: https://docs.mapbox.com/help/glossary/mbtiles/

**differences between the files**
- images in png format/pbf format
- metadata --> json

**There are 2 options for me**
- fix the file
- get a different tileserver

**Comment by csytsma** [comment]
What tileserver are you using? Have you tried viewing the MBTile file in another viewer?

I’ve noticed that the MBTile files now have more metadata, and don’t work in MapTiler iOS app. But the file still works in other viewers. 

Can you send a link to download a sample MBTile file for us to take a look at?

**Comment by BenjaminQuandt** [comment]
I use a docker image for the tileserver from here: http://tileserver.org/ | https://hub.docker.com/r/klokantech/tileserver-gl/
The sample file from mapbox do you get from here: https://docs.mapbox.com/help/glossary/mbtiles/

Thanks for the fast reply. If you need more information or my tilemill export file let me know.

**Comment by csytsma** [comment]
Klokantech makes the tileserver you're using, as well as the MapTiler GeoEditor app I use on iOS, which also fails.  When I open my MBTiles file created from current version of TileMill, it opens just fine in other applications though.  So I suspect that the latest version of Mapnik has changed something in how the MBTiles format is exported, and klokantech's core services are stumbling when trying to open it.

Can you see any log entries that show errors?

Try running the older version of TileMill (v0.10.x), and see if the MBTiles it exports work in your instance. This has worked for me.

**Comment by BenjaminQuandt** [comment]
I can check this on Monday I think. I let you know whan I have news there.
You said it opens easy in other applications. Do you have one (link/name) that work out of the box that I can use to check that my file work at all?

**Comment by csytsma** [comment]
On iOS, I use MBTiles GPS. It's a bit funky UI though.

On MacOS, I use Maptiler Desktop v9.1-1. Which is made by Klokantech, but it works for my MBTiles.

**Comment by BenjaminQuandt** [comment]
Sorry for my late response. I will use the klokantech/tileserver-php for now. Here I had the Problem that i can't use the mbtiles file. I used mbutils to extract it. This looks like It will work for me.

**Comment by csytsma** [comment]
@BenjaminQuandt thanks for following-up.  Can you be more specific about which metadata in the json you needed to remove? We could potentially update the export process to not include that data going forward.

**Comment by BenjaminQuandt** [comment]
I have some trouble to handle the text in there it has 452127characters

The data looks like this:
https://pastebin.com/tME6vewW

Here you find some Stylesheet data, layer data, tiles data and grids data. In the Layer data you find a Datasource. Here you have queries that getting the data out of the postgis.

I don't know what exactly caused the problem here but I don't think need anything of this so I droped it all.

**Comment by netkenny** [comment]
Hello,

I have fixed this myself, by just adding the "format" = "png" in the SQLite metadata table, see here:

![image](https://user-images.githubusercontent.com/45790937/104188598-c02ca900-5419-11eb-81a2-bcec205a2045.png)

**Comment by BenjaminQuandt** [comment]
oh, that's interesting. thank you for letting me know this.

**Comment by csytsma** [comment]
I determined something similar. The MBTiles file would not load in GaiaGPS. After talking to their tech support, they said the issue is that the format needs to be 'png', can't be png8, png16, png256 or similar. I haven't found yet where in the code it adds that. I fear it may be in Mapnik.
