### ISSUE TITLE
OSMBright tutorial only shows broken tiles

### ISSUE THREAD

**Issue by hmeine** [tilemill-project/tilemill#2727]
**Describe the bug**
I want to create a poster map of my hometown.  I am very new to tilemill, postgis etc., but I have spent *many* hours to inform myself as far as possible and to get to this setup, following the [OSM Bright Ubuntu quickstart](https://tilemill-project.github.io/tilemill/docs/guides/osm-bright-ubuntu-quickstart/) document. I have tried this multiple times, and finally think I understand (at a coarse level) what all the different components (should) do.
* I run the kartoza/postgis docker container with the default dbname ("gis"), user & pass ("docker").
* I used imposm to import the data from my home town into that DB (took around 1min. and gave informative output indicating success).
* I created my own Dockerfile for tilemill and built a tilemill docker container based on the current git and the `node:8.11` base image.
* I downloaded mapbox-osm-bright-f1c8780 and the shapefiles, adapted configure.py, and ran make.py (on the host machine, not inside the container, but `~/Documents/MapBox` was mounted into the tilemill docker container). I got no error from this step either.
* I opened tilemill via port 20009 in Firefox and found the "OSMBright" project.
* **Problem**: The default tile source(?) is "Project" and just shows broken tiles (white, with broken image icon). I can change it to "OpenStreetMap" or "OpenCycleMap" and get a working map display.
* **Tilemill Output**: I also get an error from tilemill:

      [tilemill] Client Error: TypeError: h is undefined
      [tilemill]     at http://hostname:20009/assets/tilemill/js/vendor.js:4153

If I understand correctly, choosing "Project" should make tilemill fetch data from my postgis, right? (Where does the name "Project" come from?) How can I debug why this fails?

**Environment: (Note: We are not setup to test on Linux or Windows so help may be slower on those OSs)**
 - OS & Version: Linux Ubuntu 18.04.2 LTS, but both postgis and tilemill run in docker containers
 - Browser & Version: Firefox 68.0.2 (seemed to work better than Safari 12.1.2) on macOS 10.14.6
 - Node Version: 8.11

**To Reproduce**
1. Run postgis: `docker run --name "postgis" -p 5432:5432 -v pg_data:/var/lib/postgresql --rm -t kartoza/postgis`
2. Run imposm: `imposm -U docker -d gis -m ../mapbox-osm-bright-f1c8780/imposm-mapping.py --read --write --optimize --deploy-production-tables my-downloaded.osm.pbf`
3. Build tilemill container from [this Dockerfile](https://gist.github.com/hmeine/eb301b87e06888b03d8cbf9bee45e5b7): `git clone https://github.com/tilemill-project/tilemill.git && docker build -t tilemill .`
4. Run tilemill: `docker run --rm -t --net=host --name tilemill -v ~/Documents/MapBox:/root/Documents/MapBox tilemill`
5. Ensure ~/Documents/MapBox is writeable: `sudo chown -R $(whoami) ~/Documents/MapBox`
6. `cd ../mapbox-osm-bright-f1c8780/ && ./make.py`
7. Open tilemill in browser, go to Projects, select "OSM Bright"
8. Observe broken tiles (white, with broken image icon)
9. After a while, there's a popup "Unable to reach the local TileMill Server..."

**Expected behavior**
I would expect some kind of map to appear.  My main problem is that I don't know how to debug this further. The only error message I see is the above "Client Error: TypeError: h is undefined".

**Comment by hmeine** [comment]
I think I understand better now: osm-bright needs to be inside the docker. I have updated the setup (see https://github.com/hmeine/tilemill_docker if you're interested) and it works much better now.

**Comment by csytsma** [comment]
Hans, thanks for the follow-up with your issue, glad you figured it out.  I know many people are interested in a docker solution, so this is great.
