### ISSUE TITLE
Error while installing TileMill(npm warning)

### ISSUE THREAD

**Issue by asmabee07** [tilemill-project/tilemill#2737]
I have tried installing TileMill twice and thrice on different partition of Ubuntu 18.04 and every same time I'm getting the following same error. 
I have followed this guidelines to install TileMill: https://tilemill-project.github.io/tilemill/docs/linux-install/
At step: npm install.

"npm WARN tilemill@1.1.0 No license field.

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/tilemill-project/millstone.git
npm ERR! 
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 13.234.210.38]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-12-21T11_04_43_591Z-debug.log"

![npm_warning](https://user-images.githubusercontent.com/21172269/71307255-b781c300-2411-11ea-9461-ff280f55fc39.png)

Can anyone please help me out how to resolve this error.

**Comment by csytsma** [comment]
Hi @asmabee07, did you figure it out? Would you be able to share what you needed to do to solve your issue, for other's to benefit from?

-Cory

**Comment by asmabee07** [comment]
There was a proxy server issue, I changed the network and it was successfully installed.
