### ISSUE TITLE
95% Noob trying to install TileMill 

### ISSUE THREAD

**Issue by SavageMandalore** [tilemill-project/tilemill#2746]
So I am a very basic user of coding in my programs, my GIS projects code files were a nightmare with its absolute mess.

I have downloaded the Tilemill File for my windows 10 laptop but I can not figure our how to begin the install process, Not sure how much it is my just waking up and how much it is my ignorance in this field. 

Any help is greatly appreicated.

**Comment by csytsma** [comment]
Assuming you are attempting to install > v1.1.0.  If you follow the instructions for MacOS <https://tilemill-project.github.io/tilemill/docs/mac-install/>, it walks through using a set of installation scripts.  You may need to tweak them to work in a Windows environment.

Alternatively, the Linux/Ubuntu instructions may be better suited to help: https://tilemill-project.github.io/tilemill/docs/linux-install/ <https://tilemill-project.github.io/tilemill/docs/linux-install/>. Again, you'll probably need to tweak for Windows.

If you're following the basic installation instructions found in the README, feel free to post the question/issue you're having, and we should be able to help you out. I'm sure other potential Windows users would benefit from the discussion as well.

-Cory

**Comment by csytsma** [comment]
@SavageMandalore Did you have any luck?

**Comment by SavageMandalore** [comment]
Nope just returned the product and went with another brand that didn't put a pay wall between me and the product.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by csytsma** [comment]
For the record, TileMill is 100% free, there is no pay wall or paid features or dependencies.

**Comment by SavageMandalore** [comment]
Might be free but when every page is directing you to upgrade the pay option and there is no clear way to get the product to work...yeah I felt like it was a scam product at that point...which is ashamed because aside from some hardware fails the pre tile buds where perfect as as my needs where.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by csytsma** [comment]
Would you be wiling to share at which point you are getting directed to a pay page, and a screenshot of it?  

The current distribution is a direct download from [Github](https://github.com/tilemill-project/tilemill/archive/refs/tags/v1.1.0.zip), followed by command-line installation of Node.js libraries.  Perhaps when installing a 3rd party product, like Postgres, you're getting asked to pay?

Thanks for providing feedback, so we can hopefully get this fixed.

**Comment by SavageMandalore** [comment]
No, there was no direction on where to go and what to download, aside from the phone saying I needed an app to connect the ear buds but did not say which amd all the included literature also did not say which app I needed but it did mention Tile so I downloaded that and that is where the pay buttons where.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by csytsma** [comment]
If you're trying to find an app to connect ear buds, sorry to say that has nothing to do with GIS mapping with TileMill. You must be thinking about a different product.

**Comment by SavageMandalore** [comment]
Maybe clarify the instructions to include the app that is needed and where to find it, I did not look at github but at the playstore. I checked the site and I found nothing to indicate what app I needed.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by natrius** [comment]
Out of curiosity: 
TileMill is a modern map design studio. 
It seems you try to connect your EarBuds with an Android-App. Is it possible you misread what app you should install? https://tile.com this seems like it should connect to something, but no earbuds. Maybe next time include a link to the product or the website you think you are talking about? (Especially after someone already mentions that something is not fitting in the big picture ["Leading to pay for premium" vs. "It is 100% free"]) 

Hope you are happy now anyway :)
