### ISSUE TITLE
In search of the OG windows exe version!

### ISSUE THREAD

**Issue by openSourcerer9000** [tilemill-project/tilemill#2755]
So I had been using this Windows standalone exe version and loving it. New computer, I need to install it again... and the installer is gone.

I had originally stumbled on it from here:
[https://ircama.github.io/osm-carto-tutorials/tilemill-osm-carto/](https://ircama.github.io/osm-carto-tutorials/tilemill-osm-carto/)

 # Install Tilemill
```

Install Tilemill; the latest working version at the moment should be http://tilemill.s3.amazonaws.com/dev/TileMill-v0.10.1-291-g31027ed-Setup.exe

Even if Tilemill has a [GitHub repository](https://github.com/tilemill-project/tilemill) including the most recent updates, with Windows it is suggested to proceed with the standard setup, which automatically installs and configures Mapnik/node-mapnik. A procedure to upgrade Tilemill and Mapnik over Windows without recompiling is not currently documented.
```

But this file is no longer available: 
http://tilemill.s3.amazonaws.com/dev/TileMill-v0.10.1-291-g31027ed-Setup.exe

Could someone who still has this file throw it up on github or somewhere so I can continue working with this fantastic piece of software? Thanks

**Comment by openSourcerer9000** [comment]
Hmm as in simply clone the repo, `$ npm install`, `$ npm run` ? I don't see that mentioned in the README. 

Before I found tilemill I was trying to install mapnik and I had to use linux. Docker is also a nightmare in Windows. You need Docker Desktop, which breaks any VM's you have set up and is generally just spamware that pops up unannounced every few minutes.

**Comment by openSourcerer9000** [comment]
Ah I just skipped over the OSX instructions lol

**Comment by csytsma** [comment]
Yeah, we don't have Windows machines, so aren't able to test it, but would love someone to test and provide feedback/improvements for installing on Windows with the bash scripts we wrote.

The bash scripts to do most of the installation and Postgres  database setup for you. They were written for MacOS, so not sure how compatible on Windows 10's bash shell.
https://tilemill-project.github.io/tilemill/docs/mac-install/ <https://tilemill-project.github.io/tilemill/docs/mac-install/>

**Comment by openSourcerer9000** [comment]
Why not just update the .exe? It takes the guesswork out of it

**Comment by csytsma** [comment]
I have no idea how to update a windows .exe, but would love your help to do it for the project?

**Comment by prusswan** [comment]
> I uploaded this version to Releases <https://github.com/tilemill-project/tilemill/releases>, so it's easy to find in the future. Have you guys tried the newer version, v1.1.0 using Node install? We've had very little feedback on how it installs or works on a Windows machine. The newer version has some better Static Maps/Print options, if that's of any interest.

Most of the problem has to do with building node-mapnik on Windows. mathisloge managed to do it with mapnik/node-mapnik#976 using vcpkg + cmake, so I am trying to build his fork and see how to proceed from there. One problem is that he seems to be building against latest mapnik so not sure how Tilemill will work, the other one is that it took hours to build mapnik on Windows (I am starting to see why Windows support was dropped)

**Comment by csytsma** [comment]
If we need to upgrade the Tilemill project to the latest Mapnik, we might be able to do that.

**Comment by prusswan** [comment]
@mathisloge could you update your branch such that `npm install https://github.com/mathisloge/node-mapnik.git` will just work?  I believe there are some manual steps used to create https://www.npmjs.com/package/@mathisloge/mapnik (for example, while I was able to build your node-mapnik using VS2019 and latest vcpkg/Python, I did not understand how to force it to build/bundle with napi-v3). If that happens, you would have completed 90% of the work to get latest Tilemill to work on Windows. (cheers!)

**Comment by mathisloge** [comment]
@prusswan normally a `npm install` in node-mapnik should be enough. The problem with `npm install https://github.com/mathisloge/node-mapnik.git` is that it won't clone the submodules of the git repo. Furthermore the vcpkg git repo have to be manually cloned into the node-mapnik root. 

I'm still not sure how to tackle these things in the best possible way. 


As my life is currently a bit short on time for "free time projects" I think I can only work on this at the earliest in august... Sorry!

**Comment by csytsma** [comment]
Neither of us have a Windows machine, nor have experience creating windows executables. How about you update the .exe?

**Comment by prusswan** [comment]
@csytsma This will require the forked version of node-mapnik by mathisloge which has yet to be merged into the main node-map nik. Update of node version (to 12 at least) will be needed as well. If you or other maintainers are comfortable with this, you can prepare the node12 branch (check mine to see the stuff I had to upgrade) and get it to work with the forked node-mapnik in your environments. The packaging can come later.
