### ISSUE TITLE
Mac M1 Error: Install of TileMill failed

### ISSUE THREAD

**Issue by pankus** [tilemill-project/tilemill#2759]
Unfortunately, I can not install Tilemill on my new Mac

[2022-09-02T01_15_42_262Z-debug-0.log](https://github.com/tilemill-project/tilemill/files/9479597/2022-09-02T01_15_42_262Z-debug-0.log)

**Comment by csytsma** [comment]
Incorrect version of Node being used.

Node.js: (earlier Node.js versions may work, but are not tested)
- Ubuntu: v8.11.x
- OSX: v8.15.x lts/carbon

From your install log:
2036 error node-pre-gyp info using **node@17.8.0** | darwin | arm64

Set your node version using nvm (or similar) and retry.   Closing bug.

**Comment by pankus** [comment]
the script ~/tilemill/utils/installtilemill.sh indeed try to install node v8.17.0, but the terminal says "ERROR: npm is known not to run on Node.js v8.17.0".
After that, I presume it uses node@17.8.0

Well, if I manually install node 8.15 ( nvm install v8.15.0 ) I can use the command "npm install" but the installation fail with the following message:

```bash
amigo@MBP tilemill % npm install
npm WARN tilemill@1.0.1 No license field.

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/florianf/bones.git
npm ERR!
npm ERR! undefined
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/amigo/.npm/_logs/2022-09-03T03_46_08_346Z-debug.log
```
