### ISSUE TITLE
Displaying to all IP's, not just localhost.

### ISSUE THREAD

**Issue by jqtrde** [tilemill-project/tilemill#296]
Is there a way to have tilemill display to all IPs, rather than just localhost?
IE, in django, you can 'runserver 0.0.0.0:8000', which pushes to all IP's, whereas the default just pushes to localhost, like tilemill does here.

I ask because I do much of my work on Linode, so there's no way to view my work.

Thanks in advance.

**Comment by Sjord** [comment]
I also had this issue, and the above comment by @kkaefer is no longer correct with current TileMill versions. The host that TileMill listens on is configured by the configuration directive listenHost. E.g. in ~/.tilemill/config.json:

```
{
	"listenHost": "0.0.0.0"
}
```

You probably also want to configure coreUrl and tileUrl, as described in #1248.
