### ISSUE TITLE
allow querying of features via single click or other event

### ISSUE THREAD

**Issue by springmeyer** [tilemill-project/tilemill#393]
Mapnik supports querying features via both pixel coordinates (on a given tile) and geo coordinates via the map.query_point and map.query_map_point functions.

In tilemill we could easily route something like the single browser click (depending on interaction effects) to send a request to tilelive and return the features at that point - this could be really nice for providing instant feedback on why a style is not properly being applied to a feature.

To get this working we'd need:
- node-mapnik to [expose the query_point and query_map_point functions off the map](https://github.com/mapnik/node-mapnik/issues/35)
- tilelive to provide an endpoint like /z/x/y.png?px=10&py=40 (where px,py are pixel coordinates on the tile) or /x=-122&y=48 (where x and y are geo coordinates in long lat or the map srs).
- tilemill to provide the click events and UI for displaying feature results

**Comment by csytsma** [comment]
This can be roughly accomplished by using the UTF grid. Closing.
