### ISSUE TITLE
incorrect location for application data on MacOS

### ISSUE THREAD

**Issue by markabur** [tilemill-project/tilemill#629]
After trying TileMill I noticed that it had created new "MapBox" folder in my ~/Documents folder. On MacOS, application support files should go somewhere in ~/Library -- ~/Documents is for user-generated files/folders. Please see:

http://www.google.com/search?q=%22Don’t+Pollute+User+Space%22

**Comment by csytsma** [comment]
It makes sense that `cache` and `app.db` get installed in ~/Library. The rest of the user project files should stay in a user location, like ~/Documents.
