### ISSUE TITLE
Manual: http://localhost:8889

### ISSUE THREAD

**Issue by mroswell** [tilemill-project/tilemill#973]
http://localhost:8889/#!/manual/0202-02-01-usage.md

The information is there, for very careful and expert readers... but I think steps such as listing the full Localhost URL might be helpful. See below for a sample:
1. Run the TileMill application
2. (Optional) Visit http://localhost:8889, if you wish to have a browser-based interface to the application.
3. (Optional) Do the following, if you want to change the default port....
   (When writing the port-changing steps, be sure to provide a suggested filename and appropriate directory for the file.)

Also, provide access to the Manual (not just the Carto reference) from within a map, not just from the overview page.

**Comment by tpotter7** [comment]
Have changed TileMill to be browser based and not standalone. When we get back around to offering a standalone version, we will work on documentation updates at that time about the two methods of running TileMill. For now, the documentation has been updated for browser based.
